/**
 * iso27001-mcp — Evidence Document MCP Resource
 *
 * Registers one resource template (viewer auth required):
 *
 *   iso27001://evidence-document/{document_id}
 *     Generated evidence document with full rendered Markdown content.
 *     List callback enumerates all generated documents ordered by
 *     created_at DESC, grouped by template_type label.
 */

import { ResourceTemplate } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { McpServer }   from "@modelcontextprotocol/sdk/server/mcp.js";
import type { ReadResourceResult } from "@modelcontextprotocol/sdk/types.js";
import { getDb }           from "../db/connection.js";
import { fromJsonArray }   from "../db/dal.js";
import { assertResourceAuth } from "./resource-auth.js";

// ── Types ─────────────────────────────────────────────────────

interface GeneratedEvidenceRow {
  id:                string;
  template_type:     string;
  title:             string;
  content:           string;
  organisation_name: string;
  generated_by:      string;
  clause_mappings:   string | null;
  control_mappings:  string | null;
  template_vars:     string;
  evidence_id:       string | null;
  created_at:        string;
}

// ── Human-readable labels for list descriptions ───────────────

const TEMPLATE_LABELS: Record<string, string> = {
  access_review_attestation:       "Access Review Attestation",
  training_acknowledgement:        "Training Acknowledgement",
  supplier_security_questionnaire: "Supplier Security Questionnaire",
  incident_post_mortem:            "Incident Post-Mortem",
  bcp_test_report:                 "BCP Test Report",
  risk_treatment_sign_off:         "Risk Treatment Sign-Off",
};

// ── Registration ──────────────────────────────────────────────

export function registerEvidenceDocumentResources(server: McpServer): void {

  // ── iso27001://evidence-document/{document_id} ───────────────
  server.resource(
    "iso27001-evidence-document",
    new ResourceTemplate("iso27001://evidence-document/{document_id}", {
      list: () => {
        const rows = getDb()
          .prepare(
            `SELECT id, template_type, title, generated_by, evidence_id, created_at
               FROM generated_evidence
              ORDER BY created_at DESC`,
          )
          .all() as Pick<
            GeneratedEvidenceRow,
            "id" | "template_type" | "title" | "generated_by" | "evidence_id" | "created_at"
          >[];

        return {
          resources: rows.map((r) => ({
            uri:         `iso27001://evidence-document/${r.id}`,
            name:        r.title,
            description: `${TEMPLATE_LABELS[r.template_type] ?? r.template_type} — generated by ${r.generated_by} on ${r.created_at.slice(0, 10)}`,
            mimeType:    "application/json",
          })),
        };
      },
    }),
    {
      description:
        "Generated ISO 27001 evidence document with full rendered Markdown content. " +
        "Template types: access_review_attestation, training_acknowledgement, " +
        "supplier_security_questionnaire, incident_post_mortem, bcp_test_report, " +
        "risk_treatment_sign_off. Fields: id, template_type, title, content (Markdown), " +
        "organisation_name, generated_by, clause_mappings, control_mappings, " +
        "template_vars, evidence_id, created_at.",
      mimeType: "application/json",
    },
    (uri, variables, extra): ReadResourceResult => {
      assertResourceAuth(extra);

      const { document_id } = variables as { document_id: string };
      const db = getDb();

      const row = db
        .prepare("SELECT * FROM generated_evidence WHERE id = ?")
        .get(document_id) as GeneratedEvidenceRow | undefined;

      if (!row) {
        throw new Error(
          `Evidence document not found: '${document_id}'. Use list_evidence_documents to find valid IDs.`,
        );
      }

      const payload = {
        ...row,
        clause_mappings:  fromJsonArray<string>(row.clause_mappings),
        control_mappings: fromJsonArray<string>(row.control_mappings),
        template_vars:    (() => {
          try { return JSON.parse(row.template_vars) as Record<string, string>; }
          catch { return {}; }
        })(),
      };

      return {
        contents: [{
          uri:      uri.toString(),
          mimeType: "application/json",
          text:     JSON.stringify(payload, null, 2),
        }],
      };
    },
  );
}
