#!/usr/bin/env python3
"""Generate clause-requirements.json for ISO 27001:2022 clauses 4-10."""
import json, os

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "seed")
os.makedirs(OUT, exist_ok=True)

# Clause requirements for ISO 27001:2022 mandatory clauses (4-10)
# Format: clause_id, parent_id (null for top-level), title, requirement_text, implementation_notes, related_controls
CLAUSES = [
  # ── Clause 4: Context of the organisation ────────────────────────────────
  {"clause_id":"4","parent_id":None,"title":"Context of the organisation","requirement_text":"The organisation shall determine external and internal issues that are relevant to its purpose and that affect its ability to achieve the intended outcome(s) of its information security management system.","implementation_notes":"Review annually and when significant changes occur. Document findings in a context register. Consider PESTLE analysis for external factors and SWOT for internal factors.","related_controls":["5.1","5.31"]},
  {"clause_id":"4.1","parent_id":"4","title":"Understanding the organisation and its context","requirement_text":"The organisation shall determine external and internal issues that are relevant to its purpose and that affect its ability to achieve the intended outcome(s) of its information security management system.","implementation_notes":"External issues include legal, regulatory, financial, technological, competitive, market, cultural, social and economic factors. Internal issues include values, culture, knowledge, performance and structure. Document issues that may pose risks or opportunities.","related_controls":["5.1","5.31"]},
  {"clause_id":"4.2","parent_id":"4","title":"Understanding the needs and expectations of interested parties","requirement_text":"The organisation shall determine: a) the interested parties that are relevant to the information security management system; b) the relevant requirements of these interested parties; c) which of these requirements will be addressed through the information security management system.","implementation_notes":"Interested parties include customers, regulators, suppliers, shareholders, employees, and partners. Document their requirements. Review and update when relationships change. Map requirements to ISMS scope and controls.","related_controls":["5.19","5.20","5.31"]},
  {"clause_id":"4.3","parent_id":"4","title":"Determining the scope of the information security management system","requirement_text":"The organisation shall determine the boundaries and applicability of the information security management system to establish its scope. When determining this scope, the organisation shall consider: a) the external and internal issues referred to in 4.1; b) the requirements referred to in 4.2; c) interfaces and dependencies between activities performed by the organisation, and those that are performed by other organisations.","implementation_notes":"Scope should be documented and available as a maintained document. Clearly define what is included and excluded. Exclusions must be justified. Consider organisational boundaries, locations, assets, and technology. The scope must be a maintained document.","related_controls":["5.1"]},
  {"clause_id":"4.4","parent_id":"4","title":"Information security management system","requirement_text":"The organisation shall establish, implement, maintain and continually improve an information security management system, including the processes needed and their interactions, in accordance with the requirements of this document.","implementation_notes":"The ISMS is a systematic approach to managing sensitive information. Document the processes and their interactions. Assign process owners. Establish monitoring and measurement mechanisms. Plan for continual improvement.","related_controls":["5.1","5.2","5.35","5.36"]},

  # ── Clause 5: Leadership ─────────────────────────────────────────────────
  {"clause_id":"5","parent_id":None,"title":"Leadership","requirement_text":"Top management shall demonstrate leadership and commitment with respect to the information security management system by taking accountability for the effectiveness of the information security management system.","implementation_notes":"Leadership engagement is critical to ISMS success. Document management's commitment through policy endorsement, resource allocation, and active participation in reviews.","related_controls":["5.1","5.2","5.4"]},
  {"clause_id":"5.1","parent_id":"5","title":"Leadership and commitment","requirement_text":"Top management shall demonstrate leadership and commitment with respect to the information security management system by: a) ensuring the information security policy and the information security objectives are established and are compatible with the strategic direction of the organisation; b) ensuring the integration of the information security management system requirements into the organisation's processes; c) ensuring that the resources needed for the information security management system are available; d) communicating the importance of effective information security management and of conforming to the information security management system requirements; e) ensuring that the information security management system achieves its intended outcome(s); f) directing persons to contribute to the effectiveness of the information security management system; g) promoting continual improvement; h) supporting other relevant management roles to demonstrate their leadership as it applies to their areas of responsibility.","implementation_notes":"Evidence of leadership commitment includes signed policy documents, management meeting minutes discussing ISMS, resource allocation records, and management review records. Top management should be able to articulate the ISMS scope and objectives.","related_controls":["5.1","5.4"]},
  {"clause_id":"5.2","parent_id":"5","title":"Policy","requirement_text":"Top management shall establish an information security policy that: a) is appropriate to the purpose of the organisation; b) includes information security objectives or provides the framework for setting information security objectives; c) includes a commitment to satisfy applicable requirements related to information security; d) includes a commitment to continual improvement of the information security management system. The information security policy shall: be available as documented information; be communicated within the organisation; be available to interested parties, as appropriate.","implementation_notes":"The policy should be a concise, high-level document approved by the most senior appropriate manager. It should be reviewed and updated at least annually. Evidence of communication should be retained (e.g. email records, training attendance).","related_controls":["5.1"]},
  {"clause_id":"5.3","parent_id":"5","title":"Organisational roles, responsibilities and authorities","requirement_text":"Top management shall ensure that the responsibilities and authorities for roles relevant to information security are assigned and communicated. Top management shall assign the responsibility and authority for: a) ensuring that the information security management system conforms to the requirements of this document; b) reporting on the performance of the information security management system to top management.","implementation_notes":"Roles may include CISO, data protection officer, system owners, and process owners. Document role descriptions and authority levels. Communicate assignments via job descriptions, organisational charts, and policy documents. Ensure accountability is clear at all levels.","related_controls":["5.2","5.3"]},

  # ── Clause 6: Planning ───────────────────────────────────────────────────
  {"clause_id":"6","parent_id":None,"title":"Planning","requirement_text":"When planning for the information security management system, the organisation shall consider the issues referred to in 4.1 and the requirements referred to in 4.2 and determine the risks and opportunities that need to be addressed.","implementation_notes":"Planning integrates risk management, objectives setting, and control selection. Document the planning process and decisions. Link planning outputs to action plans with owners and timelines.","related_controls":["5.1"]},
  {"clause_id":"6.1","parent_id":"6","title":"Actions to address risks and opportunities","requirement_text":"When planning for the information security management system, the organisation shall consider the issues referred to in 4.1 and the requirements referred to in 4.2 and determine the risks and opportunities that need to be addressed to: a) ensure the information security management system can achieve its intended outcome(s); b) prevent, or reduce, undesired effects; c) achieve continual improvement.","implementation_notes":"Document risks and opportunities identified from context analysis. Define treatment plans. Integrate with the risk assessment process. Maintain a risk register. Review risks and opportunities regularly.","related_controls":["5.1","5.31"]},
  {"clause_id":"6.1.1","parent_id":"6.1","title":"General (risk and opportunity management)","requirement_text":"The organisation shall plan actions to address these risks and opportunities, and how to integrate and implement the actions into its information security management system processes, and evaluate the effectiveness of these actions.","implementation_notes":"Actions should be proportionate to the assessed risks and opportunities. Assign owners and due dates. Integrate actions into ISMS processes. Measure effectiveness using defined criteria.","related_controls":["5.1"]},
  {"clause_id":"6.1.2","parent_id":"6.1","title":"Information security risk assessment","requirement_text":"The organisation shall define and apply an information security risk assessment process that: a) establishes and maintains information security risk criteria including: 1) the risk acceptance criteria; 2) criteria for performing information security risk assessments; b) ensures that repeated information security risk assessments produce consistent, valid and comparable results; c) identifies the information security risks: 1) applies the information security risk assessment process to identify risks associated with the loss of confidentiality, integrity and availability for information within the scope of the information security management system; 2) identifies the risk owners; d) analyses the information security risks: 1) assesses the potential consequences that would result if the risks identified were to materialise; 2) assesses the realistic likelihood of the occurrence of the risks identified; 3) determines the levels of risk; e) evaluates the information security risks: 1) compares the results of risk analysis with the risk criteria established in 6.1.2 a); 2) prioritises the analysed risks for risk treatment. The organisation shall retain documented information about the information security risk assessment process.","implementation_notes":"Use a consistent risk assessment methodology. Document criteria for likelihood and impact ratings (typically 1-5 scales). Conduct risk assessments at planned intervals and when significant changes occur. Retain risk assessment records as documented information. Consider using a risk register to track all identified risks.","related_controls":["5.1","5.31"]},
  {"clause_id":"6.1.3","parent_id":"6.1","title":"Information security risk treatment","requirement_text":"The organisation shall define and apply an information security risk treatment process to: a) select appropriate information security risk treatment options, taking account of the risk assessment results; b) determine all controls that are necessary to implement the information security risk treatment option(s) chosen; c) compare the controls determined in 6.1.3 b) with those in Annex A and verify that no necessary controls have been omitted; d) produce a Statement of Applicability that contains: 1) the necessary controls; 2) justification for their inclusion; 3) whether the necessary controls are implemented or not; 4) the justification for excluding any of the controls in Annex A; e) formulate an information security risk treatment plan; f) obtain risk owners' approval of the information security risk treatment plan and acceptance of the residual information security risks. The organisation shall retain documented information about the information security risk treatment process.","implementation_notes":"Risk treatment options include modification (mitigate), retention (accept), avoidance, and sharing (transfer). The Statement of Applicability (SoA) is a mandatory document. Document justification for each Annex A control inclusion or exclusion. Risk owners must formally accept residual risks.","related_controls":["5.1","5.15","5.19","5.31"]},
  {"clause_id":"6.2","parent_id":"6","title":"Information security objectives and planning to achieve them","requirement_text":"The organisation shall establish information security objectives at relevant functions and levels. The information security objectives shall: a) be consistent with the information security policy; b) be measurable (if practicable); c) take into account applicable information security requirements, and results from risk assessment and risk treatment; d) be monitored; e) be communicated; f) be updated as appropriate; g) be available as documented information. The organisation shall retain documented information on the information security objectives.","implementation_notes":"Objectives should be SMART (Specific, Measurable, Achievable, Relevant, Time-bound). Examples: reduce critical vulnerabilities within 30 days, achieve 95% staff awareness training completion, reduce mean time to detect incidents. Review objectives at management reviews. Link objectives to risk treatment outcomes.","related_controls":["5.1","5.36"]},
  {"clause_id":"6.3","parent_id":"6","title":"Planning of changes","requirement_text":"When the organisation determines the need for changes to the information security management system, the changes shall be carried out in a planned manner.","implementation_notes":"Changes to the ISMS should be planned and managed through a formal change process. Assess the impact of proposed changes on the ISMS effectiveness. Communicate changes to relevant stakeholders. Update documentation as changes are implemented. This clause was added in the 2022 version.","related_controls":["8.32"]},

  # ── Clause 7: Support ────────────────────────────────────────────────────
  {"clause_id":"7","parent_id":None,"title":"Support","requirement_text":"The organisation shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the information security management system.","implementation_notes":"Resources include human resources (personnel with appropriate competence), infrastructure, technology, and financial resources. Document resource requirements and allocations. Review adequacy at management reviews.","related_controls":["5.2","5.4","6.3"]},
  {"clause_id":"7.1","parent_id":"7","title":"Resources","requirement_text":"The organisation shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the information security management system.","implementation_notes":"Resources include budget, personnel, tools, and time. Document resource allocation decisions. Ensure resources are adequate for the ISMS scope. Review resource adequacy at management reviews and when scope changes.","related_controls":["5.4"]},
  {"clause_id":"7.2","parent_id":"7","title":"Competence","requirement_text":"The organisation shall: a) determine the necessary competence of person(s) doing work under its control that affects its information security performance; b) ensure that these persons are competent on the basis of appropriate education, training, or experience; c) where applicable, take actions to acquire the necessary competence, and evaluate the effectiveness of the actions taken; d) retain appropriate documented information as evidence of competence.","implementation_notes":"Maintain competency records for all personnel with ISMS responsibilities. Define required competencies in job descriptions. Provide training and development. Assess competency through testing or performance review. Retain training records and certificates.","related_controls":["6.3"]},
  {"clause_id":"7.3","parent_id":"7","title":"Awareness","requirement_text":"Persons doing work under the organisation's control shall be aware of: a) the information security policy; b) their contribution to the effectiveness of the information security management system, including the benefits of improved information security performance; c) the implications of not conforming with the information security management system requirements.","implementation_notes":"Awareness should be achieved through induction training, regular refresher training, newsletters, posters, and phishing simulations. Document awareness activities. Measure awareness through testing. Ensure contractors and third parties are also made aware.","related_controls":["6.3"]},
  {"clause_id":"7.4","parent_id":"7","title":"Communication","requirement_text":"The organisation shall determine the need for internal and external communications relevant to the information security management system including: a) on what to communicate; b) when to communicate; c) with whom to communicate; d) how to communicate.","implementation_notes":"Document a communications plan covering regular management reporting, incident communications, policy updates, and regulatory notifications. Define escalation paths. Ensure communications are appropriate for the audience.","related_controls":["5.1","5.5","5.6","5.24"]},
  {"clause_id":"7.5","parent_id":"7","title":"Documented information","requirement_text":"The organisation's information security management system shall include: a) documented information required by this document; b) documented information determined by the organisation as being necessary for the effectiveness of the information security management system.","implementation_notes":"Mandatory documented information includes: scope, information security policy, risk assessment methodology, risk register, SoA, risk treatment plan, information security objectives, and evidence of monitoring. Establish a document control procedure. Version control all documents.","related_controls":["5.1","5.37"]},
  {"clause_id":"7.5.1","parent_id":"7.5","title":"General (documented information)","requirement_text":"The organisation's information security management system shall include: a) documented information required by this document; b) documented information determined by the organisation as being necessary for the effectiveness of the information security management system.","implementation_notes":"Maintain an inventory of all ISMS documented information. Clearly distinguish between mandatory and optional documentation. Ensure documents are current and accessible to those who need them.","related_controls":["5.37"]},
  {"clause_id":"7.5.2","parent_id":"7.5","title":"Creating and updating","requirement_text":"When creating and updating documented information, the organisation shall ensure appropriate: a) identification and description (e.g. a title, date, author or reference number); b) format (e.g. language, software version, graphics) and media (e.g. paper, electronic); c) review and approval for suitability and adequacy.","implementation_notes":"Establish templates for ISMS documents. Include version number, review date, and approver in all documents. Use a document management system where practical. Ensure review cycles are defined and followed.","related_controls":["5.37"]},
  {"clause_id":"7.5.3","parent_id":"7.5","title":"Control of documented information","requirement_text":"Documented information required by the information security management system and by this document shall be controlled to ensure: a) it is available and suitable for use, where and when it is needed; b) it is adequately protected (e.g. from loss of confidentiality, improper use, or loss of integrity).","implementation_notes":"Control measures include access control, version control, backup, change management, and retention periods. Define who can create, modify, and approve documents. Archive superseded documents appropriately. Protect sensitive documentation.","related_controls":["5.12","5.13","5.33","5.37"]},

  # ── Clause 8: Operation ──────────────────────────────────────────────────
  {"clause_id":"8","parent_id":None,"title":"Operation","requirement_text":"The organisation shall plan, implement, control, evaluate and maintain the processes needed to meet information security requirements, and to implement the actions determined in Clause 6.","implementation_notes":"Operational planning translates ISMS decisions into day-to-day activities. Document procedures for all significant operational processes. Monitor process performance. Manage changes to processes.","related_controls":["5.37","8.32"]},
  {"clause_id":"8.1","parent_id":"8","title":"Operational planning and control","requirement_text":"The organisation shall plan, implement, control, evaluate and maintain the processes needed to meet information security requirements, and to implement the actions determined in Clause 6, by: establishing criteria for the processes; implementing control of the processes in accordance with the criteria. Documented information shall be available to the extent necessary to have confidence that the processes have been carried out as planned. The organisation shall control planned changes and review the consequences of unintended changes, taking action to mitigate any adverse effects, as necessary. The organisation shall ensure that externally provided processes, products or services that are relevant to the information security management system are controlled.","implementation_notes":"Establish documented procedures for critical ISMS processes. Define acceptance criteria and success metrics. Monitor process performance against criteria. Control changes through change management. Address externally provided services through supplier management.","related_controls":["5.19","5.20","5.37","8.32"]},
  {"clause_id":"8.2","parent_id":"8","title":"Information security risk assessment","requirement_text":"The organisation shall perform information security risk assessments at planned intervals or when significant changes are proposed or occur, taking account of the criteria established in 6.1.2 a). The organisation shall retain documented information of the results of the information security risk assessments.","implementation_notes":"Conduct risk assessments at least annually and when significant changes occur (new systems, new regulations, major incidents, organisational changes). Use the risk assessment methodology established in 6.1.2. Retain risk assessment reports as evidence.","related_controls":["5.1","5.31"]},
  {"clause_id":"8.3","parent_id":"8","title":"Information security risk treatment","requirement_text":"The organisation shall implement the information security risk treatment plan. The organisation shall retain documented information of the results of the information security risk treatment.","implementation_notes":"Track implementation of risk treatment plans against agreed timelines. Report progress to risk owners and management. Update the risk register and SoA as treatments are implemented. Retain evidence of treatment implementation.","related_controls":["5.1","5.15","5.19","5.31"]},

  # ── Clause 9: Performance evaluation ─────────────────────────────────────
  {"clause_id":"9","parent_id":None,"title":"Performance evaluation","requirement_text":"The organisation shall evaluate the information security performance and the effectiveness of the information security management system.","implementation_notes":"Performance evaluation provides evidence of ISMS effectiveness and drives continual improvement. Use a combination of quantitative metrics and qualitative assessments. Report results to management regularly.","related_controls":["5.35","5.36"]},
  {"clause_id":"9.1","parent_id":"9","title":"Monitoring, measurement, analysis and evaluation","requirement_text":"The organisation shall determine: a) what needs to be monitored and measured, including information security processes and controls; b) the methods for monitoring, measurement, analysis and evaluation, as applicable, to ensure valid results; c) when the monitoring and measuring shall be performed; d) who shall monitor and measure; e) when the results from monitoring and measurement shall be analysed and evaluated; f) who shall analyse and evaluate these results. The organisation shall evaluate the information security performance and the effectiveness of the information security management system. The organisation shall retain appropriate documented information as evidence of the monitoring and measurement results.","implementation_notes":"Define a measurement programme with KPIs and KRIs. Examples include: number of security incidents, patch compliance rate, training completion rate, vulnerability closure time, audit findings closed. Assign owners to each metric. Report metrics at management reviews. Retain measurement records.","related_controls":["5.36","8.15","8.16"]},
  {"clause_id":"9.2","parent_id":"9","title":"Internal audit","requirement_text":"The organisation shall conduct internal audits at planned intervals to provide information on whether the information security management system: a) conforms to: 1) the organisation's own requirements for its information security management system; 2) the requirements of this document; b) is effectively implemented and maintained. The organisation shall: plan, establish, implement and maintain an audit programme(s) including the frequency, methods, responsibilities, planning requirements and reporting, which shall take into consideration the importance of the processes concerned and the results of previous audits; define the audit criteria and scope for each audit; select auditors and conduct audits to ensure objectivity and the impartiality of the audit process; ensure that the results of the audits are reported to relevant management; retain documented information as evidence of the audit programme(s) and the audit results.","implementation_notes":"Develop an annual internal audit programme covering all ISMS elements over a defined cycle. Auditors should be independent of the areas they audit. Document audit plans, checklists, findings, and reports. Track corrective actions to closure. Retain audit records.","related_controls":["5.35"]},
  {"clause_id":"9.2.1","parent_id":"9.2","title":"General (internal audit)","requirement_text":"The organisation shall conduct internal audits at planned intervals to provide information on whether the information security management system conforms to the organisation's own requirements and the requirements of this document, and is effectively implemented and maintained.","implementation_notes":"Internal audits should be risk-based, focusing on areas of greatest concern. Use standardised audit methodologies. Maintain an audit schedule. Rotate auditors where possible to maintain independence.","related_controls":["5.35"]},
  {"clause_id":"9.2.2","parent_id":"9.2","title":"Internal audit programme","requirement_text":"The organisation shall plan, establish, implement and maintain an audit programme including the frequency, methods, responsibilities, planning requirements and reporting, which shall take into consideration the importance of the processes concerned and the results of previous audits.","implementation_notes":"Document the audit programme for the year. Consider risk-based audit prioritisation. Define audit methodologies (interviews, document review, technical testing). Assign audit roles and responsibilities. Schedule audits sufficiently in advance.","related_controls":["5.35"]},
  {"clause_id":"9.3","parent_id":"9","title":"Management review","requirement_text":"Top management shall review the organisation's information security management system at planned intervals to ensure its continuing suitability, adequacy and effectiveness. The management review shall include consideration of: a) the status of actions from previous management reviews; b) changes in external and internal issues that are relevant to the information security management system; c) feedback on the information security performance, including trends in: 1) nonconformities and corrective actions; 2) monitoring and measurement results; 3) audit results; 4) fulfilment of information security objectives; d) feedback from interested parties; e) results of risk assessment and status of risk treatment plan; f) opportunities for continual improvement. The outputs of the management review shall include decisions related to continual improvement opportunities and any need for changes to the information security management system. The organisation shall retain documented information as evidence of the results of management reviews.","implementation_notes":"Conduct management reviews at least annually, more frequently if significant changes occur. Prepare a management review pack covering all agenda items. Document decisions and action items with owners and due dates. Retain management review records as documented information.","related_controls":["5.1","5.35","5.36"]},
  {"clause_id":"9.3.1","parent_id":"9.3","title":"General (management review)","requirement_text":"Top management shall review the organisation's information security management system at planned intervals to ensure its continuing suitability, adequacy and effectiveness.","implementation_notes":"Management reviews should be attended by appropriate senior management. Use a standardised agenda. Retain minutes as evidence.","related_controls":["5.1","5.4"]},
  {"clause_id":"9.3.2","parent_id":"9.3","title":"Management review inputs","requirement_text":"The management review shall include consideration of: status of actions from previous reviews; changes in external/internal issues; feedback on information security performance; feedback from interested parties; results of risk assessment and risk treatment plan status; opportunities for continual improvement.","implementation_notes":"Prepare management review inputs in advance. Include trend data where available. Present metrics and KPIs. Summarise key risks and treatment status. Include audit findings and corrective action status.","related_controls":["5.35","5.36"]},
  {"clause_id":"9.3.3","parent_id":"9.3","title":"Management review results","requirement_text":"The outputs of the management review shall include decisions related to continual improvement opportunities and any need for changes to the information security management system.","implementation_notes":"Document all decisions with clear action items, owners, and due dates. Communicate decisions to relevant stakeholders. Track action items to completion. Use management review outputs to drive ISMS improvement.","related_controls":["5.1"]},

  # ── Clause 10: Improvement ───────────────────────────────────────────────
  {"clause_id":"10","parent_id":None,"title":"Improvement","requirement_text":"The organisation shall continually improve the suitability, adequacy and effectiveness of the information security management system.","implementation_notes":"Improvement activities include corrective actions, preventive actions, and continual improvement initiatives. Track and trend nonconformities. Use improvement inputs from audits, incidents, management reviews, and performance metrics.","related_controls":["5.27","5.35","5.36"]},
  {"clause_id":"10.1","parent_id":"10","title":"Continual improvement","requirement_text":"The organisation shall continually improve the suitability, adequacy and effectiveness of the information security management system.","implementation_notes":"Establish a formal process for identifying and implementing improvements. Use Lessons Learned from incidents, audit findings, and management reviews as inputs. Track improvement initiatives to completion. Measure the effectiveness of improvements.","related_controls":["5.27"]},
  {"clause_id":"10.2","parent_id":"10","title":"Nonconformity and corrective action","requirement_text":"When a nonconformity occurs, the organisation shall: a) react to the nonconformity and, as applicable: 1) take action to control and correct it; 2) deal with the consequences; b) evaluate the need for action to eliminate the causes of the nonconformity, in order that it does not recur or occur elsewhere, by: 1) reviewing the nonconformity; 2) determining the causes of the nonconformity; 3) determining if similar nonconformities exist, or could potentially occur; c) implement any action needed; d) review the effectiveness of any corrective action taken; e) make changes to the information security management system, if necessary. Corrective actions shall be appropriate to the effects of the nonconformities encountered. The organisation shall retain documented information as evidence of: a) the nature of the nonconformities and any subsequent actions taken; b) the results of any corrective action.","implementation_notes":"Establish a formal nonconformity and corrective action procedure. Use root cause analysis techniques (5 Whys, fishbone diagram). Assign corrective actions to owners with due dates. Verify effectiveness before closing. Retain records of nonconformities and corrective actions.","related_controls":["5.27","5.35"]},
]

with open(os.path.join(OUT, "clause-requirements.json"), "w") as f:
    json.dump(CLAUSES, f, indent=2)

print(f"clause-requirements.json: {len(CLAUSES)} entries")
top_level = [c for c in CLAUSES if c["parent_id"] is None]
print(f"  Top-level clauses (4-10): {len(top_level)}")
sub = [c for c in CLAUSES if c["parent_id"] is not None]
print(f"  Sub-clauses: {len(sub)}")
