#!/usr/bin/env python3
"""Generate ISO 27001:2013 controls + version mapping + clause requirements."""
import json, os

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "seed")
os.makedirs(OUT, exist_ok=True)

# ─── ISO 27001:2013 Annex A — 114 controls ───────────────────────────────────
CONTROLS_2013 = [
  # A.5 — Information security policies (2)
  {"control_id":"A.5.1.1","version":"2013","name":"Policies for information security","theme":"Information security policies","description":"A set of policies for information security shall be defined, approved by management, published and communicated to employees and relevant external parties.","guidance":"The information security policies should address requirements from the business strategy, regulations, legislation and current and projected information security threats. At its simplest it may be a single 'information security policy' document.","control_type":["Preventive"],"related_controls":["A.5.1.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.5.1.2","version":"2013","name":"Review of the policies for information security","theme":"Information security policies","description":"The policies for information security shall be reviewed at planned intervals or if significant changes occur to ensure their continuing suitability, adequacy and effectiveness.","guidance":"The policies should have an owner who has approved management responsibility for the development, review and evaluation of the policies. Review should include assessing opportunities for improvement of the organisation's policies and approach to managing information security in response to changes to the organisational environment, business circumstances, legal conditions or technical environment.","control_type":["Preventive","Detective"],"related_controls":["A.5.1.1"],"new_in_2022":False,"iso_clause_refs":[]},

  # A.6 — Organisation of information security (7)
  {"control_id":"A.6.1.1","version":"2013","name":"Information security roles and responsibilities","theme":"Organisation of information security","description":"All information security responsibilities shall be defined and allocated.","guidance":"Allocation of information security responsibilities should be done in accordance with the information security policies. Responsibilities for the protection of individual assets and for carrying out specific information security processes shall be identified.","control_type":["Preventive"],"related_controls":["A.6.1.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.6.1.2","version":"2013","name":"Segregation of duties","theme":"Organisation of information security","description":"Conflicting duties and areas of responsibility shall be segregated to reduce opportunities for unauthorized or unintentional modification or misuse of the organization's assets.","guidance":"Care should be taken that no single person can access, modify or use assets without authorization or detection. The initiation of an event should be separated from its authorization.","control_type":["Preventive"],"related_controls":["A.6.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.6.1.3","version":"2013","name":"Contact with authorities","theme":"Organisation of information security","description":"Appropriate contacts with relevant authorities shall be maintained.","guidance":"Organisations should have procedures that specify when and by whom authorities (e.g. law enforcement, regulatory bodies, supervisory authorities) shall be contacted and how identified information security incidents shall be reported in a timely manner.","control_type":["Preventive","Corrective"],"related_controls":["A.6.1.4"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.6.1.4","version":"2013","name":"Contact with special interest groups","theme":"Organisation of information security","description":"Appropriate contacts with special interest groups or other specialist security forums and professional associations shall be maintained.","guidance":"Membership of special interest groups or forums should be considered as a means to improve knowledge about best practices and to stay up-to-date with relevant security information.","control_type":["Preventive"],"related_controls":["A.6.1.3"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.6.1.5","version":"2013","name":"Information security in project management","theme":"Organisation of information security","description":"Information security shall be addressed in project management, regardless of the type of the project.","guidance":"Information security should be integrated into the organisation's project management method(s) to ensure that information security risks are identified and addressed as part of a project.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.6.2.1","version":"2013","name":"Mobile device policy","theme":"Organisation of information security","description":"A policy and supporting security measures shall be adopted to manage the risks introduced by using mobile devices.","guidance":"When using mobile devices, special care should be taken to ensure that business information is not compromised. The mobile device policy should consider the risks of working with mobile devices in unprotected environments.","control_type":["Preventive"],"related_controls":["A.6.2.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.6.2.2","version":"2013","name":"Teleworking","theme":"Organisation of information security","description":"A policy and supporting security measures shall be implemented to protect information accessed, processed or stored at teleworking sites.","guidance":"Organisations should only authorize teleworking activities if appropriate security arrangements and controls are in place and these comply with relevant security policy.","control_type":["Preventive"],"related_controls":["A.6.2.1"],"new_in_2022":False,"iso_clause_refs":[]},

  # A.7 — Human resource security (6)
  {"control_id":"A.7.1.1","version":"2013","name":"Screening","theme":"Human resource security","description":"Background verification checks on all candidates for employment shall be carried out in accordance with relevant laws, regulations and ethics and shall be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.","guidance":"Verification checks should take into account all relevant privacy, protection of personal data and employment based legislation, and should, where permitted, include identity verification, verification of academic and professional qualifications, and independent identity checks.","control_type":["Preventive"],"related_controls":["A.7.1.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.7.1.2","version":"2013","name":"Terms and conditions of employment","theme":"Human resource security","description":"The contractual agreements with employees and contractors shall state their and the organization's responsibilities for information security.","guidance":"The contractual obligations for employees and contractors should reflect the organisation's policies for information security. Terms and conditions of employment should include responsibilities that continue after termination.","control_type":["Preventive"],"related_controls":["A.7.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.7.2.1","version":"2013","name":"Management responsibilities","theme":"Human resource security","description":"Management shall require all employees and contractors to apply information security in accordance with the established policies and procedures of the organization.","guidance":"Management responsibilities should include ensuring that employees and contractors are aware of and motivated to fulfil their information security responsibilities.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.7.2.2","version":"2013","name":"Information security awareness, education and training","theme":"Human resource security","description":"All employees of the organization and, where relevant, contractors shall receive appropriate awareness education and training and regular updates in organizational policies and procedures, as relevant for their job function.","guidance":"Security awareness training should begin at the time of joining the organisation and continue on an on-going basis to cover current policies, responsibilities, and security procedures.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.7.2.3","version":"2013","name":"Disciplinary process","theme":"Human resource security","description":"There shall be a formal and communicated disciplinary process in place to take action against employees who have committed an information security breach.","guidance":"The formal disciplinary process should not be commenced without prior verification that a breach has occurred. It should provide for a graduated response that takes into account factors such as the nature and gravity of the breach and its impact on business.","control_type":["Corrective"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.7.3.1","version":"2013","name":"Termination or change of employment responsibilities","theme":"Human resource security","description":"Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, communicated to the employee or contractor and enforced.","guidance":"Communication of termination responsibilities should include continuing legal requirements and, where appropriate, responsibilities contained within any confidentiality agreement and the terms and conditions of employment continuing for a defined period after the end of the employment.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},

  # A.8 — Asset management (10)
  {"control_id":"A.8.1.1","version":"2013","name":"Inventory of assets","theme":"Asset management","description":"Assets associated with information and information processing facilities shall be identified and an inventory of these assets shall be drawn up and maintained.","guidance":"The organisation should identify all assets and document their importance. The inventory should include information necessary to recover from a disaster, including the type of asset, format, location, backup information, license information, and business value.","control_type":["Preventive"],"related_controls":["A.8.1.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.8.1.2","version":"2013","name":"Ownership of assets","theme":"Asset management","description":"Assets maintained in the inventory shall be owned.","guidance":"Individuals, as well as other entities who have approved management responsibility for controlling the production, development, maintenance, use and security of the assets, can be designated as asset owners.","control_type":["Preventive"],"related_controls":["A.8.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.8.1.3","version":"2013","name":"Acceptable use of assets","theme":"Asset management","description":"Rules for the acceptable use of information and of assets associated with information and information processing facilities shall be identified, documented and implemented.","guidance":"Employees and external party users using or having access to the organisation's assets should be made aware of the information security requirements of the organisation's information assets associated with information and information processing facilities and resources.","control_type":["Preventive"],"related_controls":["A.8.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.8.1.4","version":"2013","name":"Return of assets","theme":"Asset management","description":"All employees and external party users shall return all of the organizational assets in their possession upon termination of their employment, contract or agreement.","guidance":"The return of assets process should be formalised. Checklist-based procedures ensure completeness.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.8.2.1","version":"2013","name":"Classification of information","theme":"Asset management","description":"Information shall be classified in terms of legal requirements, value, criticality and sensitivity to unauthorised disclosure or modification.","guidance":"Classifications and associated protective controls for information should take into account business needs for sharing or restricting information as well as legal requirements.","control_type":["Preventive"],"related_controls":["A.8.2.2","A.8.2.3"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.8.2.2","version":"2013","name":"Labelling of information","theme":"Asset management","description":"An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.","guidance":"Procedures for information labelling need to cover information assets in physical and electronic formats.","control_type":["Preventive"],"related_controls":["A.8.2.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.8.2.3","version":"2013","name":"Handling of assets","theme":"Asset management","description":"Procedures for handling assets shall be developed and implemented in accordance with the information classification scheme adopted by the organization.","guidance":"Handling procedures should be drawn up for each level of classification.","control_type":["Preventive"],"related_controls":["A.8.2.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.8.3.1","version":"2013","name":"Management of removable media","theme":"Asset management","description":"Procedures shall be implemented for the management of removable media in accordance with the classification scheme adopted by the organization.","guidance":"Guidelines for managing removable media should include procedures for protecting media containing sensitive information during transportation and procedures for destruction of such media when no longer required.","control_type":["Preventive"],"related_controls":["A.8.3.2","A.8.3.3"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.8.3.2","version":"2013","name":"Disposal of media","theme":"Asset management","description":"Media shall be disposed of securely when no longer required, using formal procedures.","guidance":"Formal procedures should be established to minimise the risk of confidential information leakage to unauthorized persons.","control_type":["Preventive"],"related_controls":["A.8.3.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.8.3.3","version":"2013","name":"Physical media transfer","theme":"Asset management","description":"Media containing information shall be protected against unauthorized access, misuse or corruption during transportation.","guidance":"Where confidentiality and integrity considerations are important, the following controls should be considered: use of locked containers, delivery by hand, tamper-evident packaging, and encrypted transfer.","control_type":["Preventive"],"related_controls":["A.8.3.1"],"new_in_2022":False,"iso_clause_refs":[]},

  # A.9 — Access control (14)
  {"control_id":"A.9.1.1","version":"2013","name":"Access control policy","theme":"Access control","description":"An access control policy shall be established, documented and reviewed based on business and information security requirements.","guidance":"Access control rules and rights for each user or group of users should be clearly stated in an access control policy. Access controls are both logical and physical.","control_type":["Preventive"],"related_controls":["A.9.1.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.1.2","version":"2013","name":"Access to networks and network services","theme":"Access control","description":"Users shall only be provided with access to the network and network services that they have been specifically authorized to use.","guidance":"A policy should be formulated concerning the use of networks and network services and should cover the networks and network services that are allowed to be accessed.","control_type":["Preventive"],"related_controls":["A.9.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.2.1","version":"2013","name":"User registration and de-registration","theme":"Access control","description":"A formal user registration and de-registration process shall be implemented to enable assignment of access rights.","guidance":"The process for managing user IDs should include using unique user IDs, verifying the authorization for access, and ensuring prompt removal of access when no longer required.","control_type":["Preventive"],"related_controls":["A.9.2.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.2.2","version":"2013","name":"User access provisioning","theme":"Access control","description":"A formal user access provisioning process shall be implemented to assign or revoke access rights for all user types to all systems and services.","guidance":"The access provisioning process should include authorisation of access by the owner of the information system or service and verification of the access level being appropriate.","control_type":["Preventive"],"related_controls":["A.9.2.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.2.3","version":"2013","name":"Management of privileged access rights","theme":"Access control","description":"The allocation and use of privileged access rights shall be restricted and controlled.","guidance":"A formal authorisation process and a record of all privileged access rights allocated should be maintained. Privileged access rights should not be shared.","control_type":["Preventive","Detective"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.2.4","version":"2013","name":"Management of secret authentication information of users","theme":"Access control","description":"The allocation of secret authentication information shall be controlled through a formal management process.","guidance":"Users should be required to sign a statement to keep secret authentication information confidential; and maintain authentication information solely for their own use.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.2.5","version":"2013","name":"Review of user access rights","theme":"Access control","description":"Asset owners shall review users' access rights at regular intervals.","guidance":"User access rights should be reviewed at regular intervals. Access rights should be reassessed following changes in employment such as promotion, demotion or termination.","control_type":["Detective"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.2.6","version":"2013","name":"Removal or adjustment of access rights","theme":"Access control","description":"The access rights of all employees and external party users to information and information processing facilities shall be removed upon termination of their employment, contract or agreement, or adjusted upon change.","guidance":"Access rights to information assets and facilities should be removed at the time of termination of their employment, contract or agreement.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.3.1","version":"2013","name":"Use of secret authentication information","theme":"Access control","description":"Users shall be required to follow the organization's practices in the use of secret authentication information.","guidance":"All users should be advised to protect secret authentication information; avoid keeping a note of secret authentication information; change secret authentication information whenever there is any indication of its possible compromise.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.4.1","version":"2013","name":"Information access restriction","theme":"Access control","description":"Access to information and application system functions shall be restricted in accordance with the access control policy.","guidance":"Restrictions on access should be based on individual application requirements and in accordance with the defined access control policy. Consideration should be given to the access restrictions requirements of the applications concerned.","control_type":["Preventive"],"related_controls":["A.9.4.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.4.2","version":"2013","name":"Secure log-on procedures","theme":"Access control","description":"Where required by the access control policy, access to systems and applications shall be controlled by a secure log-on procedure.","guidance":"A good log-on procedure should not display system or application identifiers until the log-on process has been successfully completed. It should display a general notice that the computer should only be accessed by authorized users.","control_type":["Preventive"],"related_controls":["A.9.4.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.4.3","version":"2013","name":"Password management system","theme":"Access control","description":"Password management systems shall be interactive and shall ensure quality passwords.","guidance":"A good password management system should enforce the use of individual user IDs and passwords to maintain accountability, and should allow users to select and change their own passwords and include a confirmation procedure to allow for input errors.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.4.4","version":"2013","name":"Use of privileged utility programs","theme":"Access control","description":"The use of utility programs that might be capable of overriding system and application controls shall be restricted and tightly controlled.","guidance":"Consideration should be given to the identification of all utility programs associated with the information systems, establishing need to use and authorisation, limiting use to the minimum practical number of trusted users, and controlling and monitoring use.","control_type":["Preventive","Detective"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.9.4.5","version":"2013","name":"Access control to program source code","theme":"Access control","description":"Access to program source code shall be restricted.","guidance":"Strict control needs to be kept over access to program source code and associated items such as designs, specifications, verification and validation plans, in order to prevent the introduction of unauthorized functionality and to avoid unintentional changes.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},

  # A.10 — Cryptography (2)
  {"control_id":"A.10.1.1","version":"2013","name":"Policy on the use of cryptographic controls","theme":"Cryptography","description":"A policy on the use of cryptographic controls for protection of information shall be developed and implemented.","guidance":"When developing a cryptographic policy, the following should be considered: the management approach towards the use of cryptographic controls across the organisation including the general principles under which business information should be protected; the required level of protection.","control_type":["Preventive"],"related_controls":["A.10.1.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.10.1.2","version":"2013","name":"Key management","theme":"Cryptography","description":"A policy on the use, protection and lifetime of cryptographic keys shall be developed and implemented through their whole lifecycle.","guidance":"The management of cryptographic keys is essential to the effective use of cryptographic techniques. Compromised or weak keys may compromise the encryption and authentication techniques used.","control_type":["Preventive"],"related_controls":["A.10.1.1"],"new_in_2022":False,"iso_clause_refs":[]},

  # A.11 — Physical and environmental security (15)
  {"control_id":"A.11.1.1","version":"2013","name":"Physical security perimeter","theme":"Physical and environmental security","description":"Security perimeters shall be defined and used to protect areas that contain either sensitive or critical information and information processing facilities.","guidance":"A security perimeter is something that creates a barrier around the organisation's assets, such as walls, card controlled entry gates or manned reception desks.","control_type":["Preventive"],"related_controls":["A.11.1.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.1.2","version":"2013","name":"Physical entry controls","theme":"Physical and environmental security","description":"Secure areas shall be protected by appropriate entry controls to ensure that only authorized personnel are allowed access.","guidance":"The following should be considered: the date and time of entry and departure of visitors should be recorded; visitors should only be granted access for specific, authorized purposes and should be issued with instructions on the security requirements of the area and on emergency procedures.","control_type":["Preventive","Detective"],"related_controls":["A.11.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.1.3","version":"2013","name":"Securing offices, rooms and facilities","theme":"Physical and environmental security","description":"Physical security for offices, rooms and facilities shall be designed and applied.","guidance":"Facilities should be designed and sited to avoid access by the general public. Security measures should be proportionate to the business information classification requirements of the assets contained.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.1.4","version":"2013","name":"Protecting against external and environmental threats","theme":"Physical and environmental security","description":"Physical protection against natural disasters, malicious attack or accidents shall be designed and applied.","guidance":"Specialist advice should be sought on how to avoid damage from fire, flood, earthquake, explosion, civil unrest and other forms of natural or man-made disaster.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.1.5","version":"2013","name":"Working in secure areas","theme":"Physical and environmental security","description":"Procedures for working in secure areas shall be designed and applied.","guidance":"Procedures should cover all staff working in secure areas, including third-party support staff. Procedures should include having knowledge of the existence of a secure area only on a need-to-know basis, and avoiding unsupervised working in secure areas.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.1.6","version":"2013","name":"Delivery and loading areas","theme":"Physical and environmental security","description":"Access points such as delivery and loading areas and other points where unauthorized persons could enter the premises shall be controlled and, if possible, isolated from information processing facilities to avoid unauthorized access.","guidance":"Access to the delivery and loading area from outside of the building should be restricted to identified and authorized personnel.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.2.1","version":"2013","name":"Equipment siting and protection","theme":"Physical and environmental security","description":"Equipment shall be sited and protected to reduce the risks from environmental threats and hazards, and opportunities for unauthorized access.","guidance":"The siting of equipment should minimise unnecessary access into work areas. Items requiring special protection should be isolated to reduce the general level of protection required. Controls should be adopted to minimise the risk of potential physical threats.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.2.2","version":"2013","name":"Supporting utilities","theme":"Physical and environmental security","description":"Equipment shall be protected from power failures and other disruptions caused by failures in supporting utilities.","guidance":"Supporting utilities (e.g. electricity, water supply, sewage, heating/ventilation, and air conditioning) should all be adequate for the systems they are supporting. Equipment should be regularly inspected and tested.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.2.3","version":"2013","name":"Cabling security","theme":"Physical and environmental security","description":"Power and telecommunications cabling carrying data or supporting information services shall be protected from interception, interference or damage.","guidance":"Controls should include use of conduit and routes avoiding public areas, protected distribution systems, separation of power from communications cables, and use of electromagnetic shielding.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.2.4","version":"2013","name":"Equipment maintenance","theme":"Physical and environmental security","description":"Equipment shall be correctly maintained to ensure its continued availability and integrity.","guidance":"The following guidelines for maintaining equipment should be considered: equipment should be maintained in accordance with the supplier's recommended service intervals and specifications; only authorized maintenance personnel should carry out repairs and service equipment.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.2.5","version":"2013","name":"Removal of assets","theme":"Physical and environmental security","description":"Equipment, information or software shall not be taken off-site without prior authorization.","guidance":"Equipment, information or software should only be taken off-site after appropriate authorization. A record of all equipment taken off-site should be maintained.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.2.6","version":"2013","name":"Security of equipment and assets off-premises","theme":"Physical and environmental security","description":"Security shall be applied to off-site assets taking into account the different risks of working outside the organization's premises.","guidance":"The risk of information being accessed by unauthorized persons in public places should be taken into consideration. Equipment should be protected against theft and loss at all times.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.2.7","version":"2013","name":"Secure disposal or reuse of equipment","theme":"Physical and environmental security","description":"All items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.","guidance":"Storage devices containing sensitive information should be physically destroyed or the information should be destroyed, deleted or overwritten using techniques to make the original information non-retrievable.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.2.8","version":"2013","name":"Unattended user equipment","theme":"Physical and environmental security","description":"Users shall ensure that unattended equipment has appropriate protection.","guidance":"All users should be made aware of the security requirements and procedures for protecting unattended equipment, as well as their responsibilities for implementing such protection.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.11.2.9","version":"2013","name":"Clear desk and clear screen policy","theme":"Physical and environmental security","description":"A clear desk policy for papers and removable storage media and a clear screen policy for information processing facilities shall be adopted.","guidance":"A clear desk and clear screen policy takes into account the information classification, applicable legal and contractual requirements and the corresponding risks and cultural aspects of the organisation.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},

  # A.12 — Operations security (14)
  {"control_id":"A.12.1.1","version":"2013","name":"Documented operating procedures","theme":"Operations security","description":"Operating procedures shall be documented and made available to all users who need them.","guidance":"Operating procedures should be prepared for operational activities associated with information processing and communication facilities. They should be treated as formal documents and changes authorized by management.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.1.2","version":"2013","name":"Change management","theme":"Operations security","description":"Changes to the organization, business processes, information processing facilities and systems that affect information security shall be controlled.","guidance":"Particular attention should be given to re-assessment of information security risks, identification of all staff and external users who need to be notified of changes, and ensuring that change is not carried out at critical times.","control_type":["Preventive","Detective"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.1.3","version":"2013","name":"Capacity management","theme":"Operations security","description":"The use of resources shall be monitored, tuned and projections made of future capacity requirements to ensure the required system performance.","guidance":"Capacity requirements should be identified taking into account the business criticality of the concerned system. System tuning and monitoring should be applied to ensure and, where necessary, improve the availability and efficiency of systems.","control_type":["Preventive","Detective"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.1.4","version":"2013","name":"Separation of development, testing and operational environments","theme":"Operations security","description":"Development, testing, and operational environments shall be separated to reduce the risks of unauthorized access or changes to the operational environment.","guidance":"The level of separation between operational, test and development environments needed in order to prevent operational problems is identified and appropriate controls implemented.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.2.1","version":"2013","name":"Controls against malware","theme":"Operations security","description":"Detection, prevention and recovery controls to protect against malware shall be implemented, combined with appropriate user awareness.","guidance":"Protection against malware should be based on malware detection and repair software, information security awareness, appropriate system access and change management controls.","control_type":["Preventive","Detective","Corrective"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.3.1","version":"2013","name":"Information backup","theme":"Operations security","description":"Backup copies of information, software and system images shall be taken and tested regularly in accordance with an agreed backup policy.","guidance":"The extent of backup (for example full or differential backup) and frequency should reflect the business requirements of the organisation, the security requirements of the information involved, and the criticality of the information to the continued operation of the organisation.","control_type":["Preventive","Corrective"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.4.1","version":"2013","name":"Event logging","theme":"Operations security","description":"Event logs recording user activities, exceptions, faults and information security events shall be produced, kept and regularly reviewed.","guidance":"Event logs should include user IDs, system activities, dates, times and details of events such as log-on and log-off, network access, changes to system configuration, use of privileges, and access to files and other resources.","control_type":["Detective"],"related_controls":["A.12.4.2","A.12.4.3","A.12.4.4"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.4.2","version":"2013","name":"Protection of log information","theme":"Operations security","description":"Logging facilities and log information shall be protected against tampering and unauthorized access.","guidance":"Controls should be aimed at protecting against unauthorized changes to log information such as log files being edited or deleted, and storage media being overwritten.","control_type":["Preventive","Detective"],"related_controls":["A.12.4.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.4.3","version":"2013","name":"Administrator and operator logs","theme":"Operations security","description":"System administrator and system operator activities shall be logged and the logs protected and regularly reviewed.","guidance":"System administrators and operators should maintain a log of their activities. These logs should be protected and reviewed regularly to detect malpractice or anomalies.","control_type":["Detective"],"related_controls":["A.12.4.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.4.4","version":"2013","name":"Clock synchronisation","theme":"Operations security","description":"The clocks of all relevant information processing systems within an organization or security domain shall be synchronised to a single reference time source.","guidance":"The correct setting of computer clocks is important to ensure the accuracy of audit logs, which may be required for investigations or as evidence in legal or disciplinary cases.","control_type":["Preventive"],"related_controls":["A.12.4.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.5.1","version":"2013","name":"Installation of software on operational systems","theme":"Operations security","description":"Procedures shall be implemented to control the installation of software on operational systems.","guidance":"To minimise the risk of corruption of operational systems, procedures should only allow the implementation of executable code, not development code or compilers.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.6.1","version":"2013","name":"Management of technical vulnerabilities","theme":"Operations security","description":"Information about technical vulnerabilities of information systems being used shall be obtained in a timely fashion, the organization's exposure to such vulnerabilities evaluated and appropriate measures taken to address the associated risk.","guidance":"Current and complete information about technical vulnerabilities of information systems in use is essential for vulnerability management. Action needs to be taken in a timely manner to patch known vulnerabilities.","control_type":["Preventive","Detective"],"related_controls":["A.12.6.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.6.2","version":"2013","name":"Restrictions on software installation","theme":"Operations security","description":"Rules governing the installation of software by users shall be established and implemented.","guidance":"The organisation should define and enforce a strict policy on what types of software users are allowed to install. The principle of least privilege should be applied.","control_type":["Preventive"],"related_controls":["A.12.6.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.12.7.1","version":"2013","name":"Information systems audit controls","theme":"Operations security","description":"Audit requirements and activities involving verification of operational systems shall be carefully planned and agreed to minimise disruptions to business processes.","guidance":"Requirements for audits should be agreed with management. The scope of technical audit checks should be agreed and controlled.","control_type":["Preventive","Detective"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},

  # A.13 — Communications security (7)
  {"control_id":"A.13.1.1","version":"2013","name":"Network controls","theme":"Communications security","description":"Networks shall be managed and controlled to protect information in systems and applications.","guidance":"Network managers should implement controls to ensure the security of information in networks and the protection of connected services from unauthorized access. Particular attention should be given to routing controls to ensure that computer connections and information flows do not breach the access control policy.","control_type":["Preventive","Detective"],"related_controls":["A.13.1.2","A.13.1.3"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.13.1.2","version":"2013","name":"Security of network services","theme":"Communications security","description":"Security mechanisms, service levels and management requirements of all network services shall be identified and included in network services agreements, whether these services are provided in-house or outsourced.","guidance":"The security features, service levels and management requirements for all network services should be identified and documented. Network service providers should have the ability to manage agreed services in a secure way.","control_type":["Preventive"],"related_controls":["A.13.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.13.1.3","version":"2013","name":"Segregation in networks","theme":"Communications security","description":"Groups of information services, users, and information systems shall be segregated on networks.","guidance":"One method of controlling the security of large networks is to divide them into separate network domains. Domains can be chosen based on trust levels, criticality or sensitivity of the information systems within the domains.","control_type":["Preventive"],"related_controls":["A.13.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.13.2.1","version":"2013","name":"Information transfer policies and procedures","theme":"Communications security","description":"Formal transfer policies, procedures and controls shall be in place to protect the transfer of information through the use of all types of communication facilities.","guidance":"Procedures and controls to be followed when using electronic communication facilities for information transfer include prevention of transmitted electronic messages from being intercepted, copied, modified or deleted.","control_type":["Preventive"],"related_controls":["A.13.2.2","A.13.2.3","A.13.2.4"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.13.2.2","version":"2013","name":"Agreements on information transfer","theme":"Communications security","description":"Agreements shall address the secure transfer of business information between the organization and external parties.","guidance":"Agreements on transfer of information between the organisation and external parties should reflect the sensitivity of the business information involved.","control_type":["Preventive"],"related_controls":["A.13.2.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.13.2.3","version":"2013","name":"Electronic messaging","theme":"Communications security","description":"Information involved in electronic messaging shall be appropriately protected.","guidance":"Information security considerations for electronic messaging should include: protection of messages from unauthorized access, modification or denial of service; ensuring correct addressing and transportation of the message; reliability and availability of the service.","control_type":["Preventive"],"related_controls":["A.13.2.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.13.2.4","version":"2013","name":"Confidentiality or non-disclosure agreements","theme":"Communications security","description":"Requirements for confidentiality or non-disclosure agreements reflecting the organization's needs for the protection of information shall be identified, regularly reviewed and documented.","guidance":"Confidentiality or non-disclosure agreements should address the requirement to protect confidential information using legally enforceable terms. Confidentiality agreements apply to external parties with access to the organisation's confidential information.","control_type":["Preventive"],"related_controls":["A.13.2.1"],"new_in_2022":False,"iso_clause_refs":[]},

  # A.14 — System acquisition, development and maintenance (13)
  {"control_id":"A.14.1.1","version":"2013","name":"Information security requirements analysis and specification","theme":"System acquisition, development and maintenance","description":"The information security related requirements shall be included in the requirements for new information systems or enhancements to existing information systems.","guidance":"Requirements for information systems include information systems in infrastructure, business applications, or off-the-shelf products. Information security requirements should be stated in a way to allow them to be tested.","control_type":["Preventive"],"related_controls":["A.14.1.2","A.14.1.3"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.14.1.2","version":"2013","name":"Securing application services on public networks","theme":"System acquisition, development and maintenance","description":"Information involved in application services passing over public networks shall be protected from fraudulent activity, contract dispute and unauthorized disclosure and modification.","guidance":"Application services exposed to public networks face significant security challenges requiring specific controls to protect against incomplete transmission, mis-routing, unauthorized message alteration, unauthorized disclosure, unauthorized message duplication or replay, and repudiation.","control_type":["Preventive"],"related_controls":["A.14.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.14.1.3","version":"2013","name":"Protecting application services transactions","theme":"System acquisition, development and maintenance","description":"Information involved in application service transactions shall be protected to prevent incomplete transmission, mis-routing, unauthorized message alteration, unauthorized disclosure, unauthorized message duplication or replay.","guidance":"Controls for transaction security include the use of cryptographic techniques, use of secure protocols, and ensuring access is restricted to authorised users only.","control_type":["Preventive"],"related_controls":["A.14.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.14.2.1","version":"2013","name":"Secure development policy","theme":"System acquisition, development and maintenance","description":"Rules for the development of software and systems shall be established and applied to developments within the organization.","guidance":"Secure development practices include security in development methodology, secure coding guidelines, information security knowledge and education, ability to test and prove security, a secure development environment, and production data not used in development and test environments.","control_type":["Preventive"],"related_controls":["A.14.2.2","A.14.2.5"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.14.2.2","version":"2013","name":"System change control procedures","theme":"System acquisition, development and maintenance","description":"Changes to systems within the development lifecycle shall be controlled by the use of formal change control procedures.","guidance":"Formal change control procedures should be documented and enforced in order to minimise the corruption of information systems. Procedures should cover formal documentation of requested changes, impact assessment, test plans and rollback procedures.","control_type":["Preventive","Detective"],"related_controls":["A.14.2.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.14.2.3","version":"2013","name":"Technical review of applications after operating platform changes","theme":"System acquisition, development and maintenance","description":"When operating platforms are changed, business critical applications shall be reviewed and tested to ensure there is no adverse impact on organizational operations or security.","guidance":"This process should cover risk assessment of the operating platform changes and impact on existing system security controls and integrity procedures.","control_type":["Preventive","Detective"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.14.2.4","version":"2013","name":"Restrictions on changes to software packages","theme":"System acquisition, development and maintenance","description":"Modifications to software packages shall be discouraged, limited to necessary changes and all changes shall be strictly controlled.","guidance":"Where possible and practicable, vendor supplied software packages should be used without modification. Modifications should be limited to changes that are strictly necessary.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.14.2.5","version":"2013","name":"Secure system engineering principles","theme":"System acquisition, development and maintenance","description":"Principles for engineering secure systems shall be established, documented, maintained and applied to any information system implementation efforts.","guidance":"Secure engineering principles include the application of security in all architectural layers (business, data, application and technology), analyse security in each application layer using structured security design techniques, and security control engineering techniques.","control_type":["Preventive"],"related_controls":["A.14.2.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.14.2.6","version":"2013","name":"Secure development environment","theme":"System acquisition, development and maintenance","description":"Organizations shall establish and appropriately protect secure development environments for system development and integration efforts that cover the entire system development lifecycle.","guidance":"A secure development environment includes people, processes and technology associated with system development and integration. Consideration should be given to physical and logical access to the development environment, monitoring of and control over changes.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.14.2.7","version":"2013","name":"Outsourced development","theme":"System acquisition, development and maintenance","description":"The organization shall supervise and monitor the activity of outsourced system development.","guidance":"Where software development is outsourced, the organization should supervise and monitor all activities related to outsourced software development in order to ensure that the activities comply with its policies.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.14.2.8","version":"2013","name":"System security testing","theme":"System acquisition, development and maintenance","description":"Testing of security functionality shall be carried out during development.","guidance":"New and updated systems require thorough testing and verification during the development process. Security testing should include testing of security controls within the new system to ensure they have been implemented correctly.","control_type":["Preventive","Detective"],"related_controls":["A.14.2.9"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.14.2.9","version":"2013","name":"System acceptance testing","theme":"System acquisition, development and maintenance","description":"Acceptance testing programs and related criteria shall be established for new information systems, upgrades and new versions.","guidance":"Tests should be designed to ensure that all security requirements are met by the new systems or their updates. Acceptance criteria should be established and tests documented before testing commences.","control_type":["Preventive","Detective"],"related_controls":["A.14.2.8"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.14.3.1","version":"2013","name":"Protection of test data","theme":"System acquisition, development and maintenance","description":"Test data shall be selected carefully, protected and controlled.","guidance":"Operational data (live data from production) should be avoided for use in testing. If operational data is used it should be anonymised before use. Sensitive information that has been used for testing should be deleted once testing is complete.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},

  # A.15 — Supplier relationships (5)
  {"control_id":"A.15.1.1","version":"2013","name":"Information security policy for supplier relationships","theme":"Supplier relationships","description":"Information security requirements for mitigating the risks associated with supplier's access to the organization's assets shall be agreed with the supplier and documented.","guidance":"Suppliers should adhere to the information security requirements of the organisation as documented in an information security policy for supplier relationships or as specific policies covering specific types of suppliers.","control_type":["Preventive"],"related_controls":["A.15.1.2","A.15.1.3"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.15.1.2","version":"2013","name":"Addressing security within supplier agreements","theme":"Supplier relationships","description":"All relevant information security requirements shall be established and agreed with each supplier that may access, process, store, communicate, or provide IT infrastructure components for, the organization's information.","guidance":"Supplier agreements should cover requirements to protect information and assets based on the level of access required, identification of the types of information that can be accessed or provided to the supplier, and data breach notification procedures.","control_type":["Preventive"],"related_controls":["A.15.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.15.1.3","version":"2013","name":"Information and communication technology supply chain","theme":"Supplier relationships","description":"Agreements with suppliers shall include requirements to address the information security risks associated with information and communications technology services and product supply chain.","guidance":"Topics to consider in supplier agreements related to ICT supply chain include requirements for suppliers to propagate the appropriate information security practices throughout the supply chain if the supplier subcontracts parts of the service to other suppliers.","control_type":["Preventive"],"related_controls":["A.15.1.1","A.15.1.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.15.2.1","version":"2013","name":"Monitoring and review of supplier services","theme":"Supplier relationships","description":"Organizations shall regularly monitor, review and audit supplier service delivery.","guidance":"Monitoring and review of supplier services should ensure that the information security terms and conditions of the agreements are being adhered to, and that information security incidents and problems are managed properly.","control_type":["Detective"],"related_controls":["A.15.2.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.15.2.2","version":"2013","name":"Managing changes to supplier services","theme":"Supplier relationships","description":"Changes to the provision of services by suppliers, including maintaining and improving existing information security policies, procedures and controls, shall be managed, taking account of the criticality of business information, systems and processes involved and re-assessment of risks.","guidance":"Account needs to be taken of the business criticality of the information involved and the implications of any changes when identifying how the information security policies and procedures need to be modified.","control_type":["Preventive","Detective"],"related_controls":["A.15.2.1"],"new_in_2022":False,"iso_clause_refs":[]},

  # A.16 — Information security incident management (7)
  {"control_id":"A.16.1.1","version":"2013","name":"Responsibilities and procedures","theme":"Information security incident management","description":"Management responsibilities and procedures shall be established to ensure a quick, effective and orderly response to information security incidents.","guidance":"Incident management procedures should cover the types of information security events or incidents that could occur, who is involved in detecting, reporting and responding to incidents, and the level of management authority and reporting chain required.","control_type":["Preventive","Corrective"],"related_controls":["A.16.1.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.16.1.2","version":"2013","name":"Reporting information security events","theme":"Information security incident management","description":"Information security events shall be reported through appropriate management channels as quickly as possible.","guidance":"A formal event reporting procedure should be established, together with an incident response and escalation procedure, setting out the action to be taken on receipt of a report of an information security event.","control_type":["Detective"],"related_controls":["A.16.1.1","A.16.1.3"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.16.1.3","version":"2013","name":"Reporting information security weaknesses","theme":"Information security incident management","description":"Employees and contractors using the organization's information systems and services shall be required to note and report any observed or suspected information security weaknesses in systems or services.","guidance":"All employees and contractors should be made aware of their responsibility to report information security weaknesses as quickly as possible in order to prevent information security incidents.","control_type":["Detective"],"related_controls":["A.16.1.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.16.1.4","version":"2013","name":"Assessment of and decision on information security events","theme":"Information security incident management","description":"Information security events shall be assessed and it shall be decided if they are to be classified as information security incidents.","guidance":"A point of contact should be designated for the assessment of information security events and making decisions on whether they are to be treated as information security incidents.","control_type":["Detective"],"related_controls":["A.16.1.2","A.16.1.5"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.16.1.5","version":"2013","name":"Response to information security incidents","theme":"Information security incident management","description":"Information security incidents shall be responded to in accordance with the documented procedures.","guidance":"The designated point of contact and other persons in the organization should collect evidence as early as possible after an information security incident has occurred. Formal procedures for responding to information security incidents need to be established.","control_type":["Corrective"],"related_controls":["A.16.1.4","A.16.1.6"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.16.1.6","version":"2013","name":"Learning from information security incidents","theme":"Information security incident management","description":"Knowledge gained from analysing and resolving information security incidents shall be used to reduce the likelihood or impact of future incidents.","guidance":"Mechanisms should be put in place to enable the types, volumes, and costs of information security incidents to be quantified and monitored. The information gained from the evaluation of past information security incidents should be used to identify recurring or high impact incidents.","control_type":["Preventive","Corrective"],"related_controls":["A.16.1.5"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.16.1.7","version":"2013","name":"Collection of evidence","theme":"Information security incident management","description":"The organization shall define and apply procedures for the identification, collection, acquisition and preservation of information, which can serve as evidence.","guidance":"Internal procedures should be developed and followed when collecting and preserving evidence for the purposes of disciplinary and legal action. In general, these procedures for the preservation of evidence should provide for the chain of custody.","control_type":["Detective","Corrective"],"related_controls":["A.16.1.5"],"new_in_2022":False,"iso_clause_refs":[]},

  # A.17 — Information security aspects of business continuity management (4)
  {"control_id":"A.17.1.1","version":"2013","name":"Planning information security continuity","theme":"Information security aspects of business continuity management","description":"The organization shall determine its requirements for information security and the continuity of information security management in adverse situations, e.g. during a crisis or disaster.","guidance":"The organisation should determine whether information security continuity is included within the business continuity management process, or whether it is managed separately. A designated business continuity management function should be established.","control_type":["Preventive"],"related_controls":["A.17.1.2","A.17.1.3"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.17.1.2","version":"2013","name":"Implementing information security continuity","theme":"Information security aspects of business continuity management","description":"The organization shall establish, document, implement and maintain processes, procedures and controls to ensure the required level of continuity for information security during an adverse situation.","guidance":"These plans should address the maintenance of appropriate security controls under adverse conditions. The security controls implemented in normal operating conditions may not function effectively in the event of a disaster or emergency.","control_type":["Preventive","Corrective"],"related_controls":["A.17.1.1","A.17.1.3"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.17.1.3","version":"2013","name":"Verify, review and evaluate information security continuity","theme":"Information security aspects of business continuity management","description":"The organization shall verify the established and implemented information security continuity controls at regular intervals in order to ensure that they are valid and effective during adverse situations.","guidance":"Changes in processes, procedures, technology and tools relating to the continuity of information security should be identified and controls updated to remain effective.","control_type":["Preventive","Detective"],"related_controls":["A.17.1.1","A.17.1.2"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.17.2.1","version":"2013","name":"Availability of information processing facilities","theme":"Information security aspects of business continuity management","description":"Information processing facilities shall be implemented with sufficient redundancy to meet availability requirements.","guidance":"The redundancy of information processing systems can be achieved by duplicating components or architectures. Redundancy needs to be tested to ensure that failover from one component to another works as expected.","control_type":["Preventive"],"related_controls":[],"new_in_2022":False,"iso_clause_refs":[]},

  # A.18 — Compliance (8)
  {"control_id":"A.18.1.1","version":"2013","name":"Identification of applicable legislation and contractual requirements","theme":"Compliance","description":"All relevant legislative statutory, regulatory, contractual requirements and the organization's approach to meet these requirements shall be explicitly identified, documented and kept up to date for each information system and the organization.","guidance":"Legal requirements vary from one jurisdiction to another and may vary for information created in one country that is transmitted to another country. Specific controls and individual responsibilities to meet these requirements should be defined and documented.","control_type":["Preventive"],"related_controls":["A.18.1.2","A.18.1.3","A.18.1.4","A.18.1.5"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.18.1.2","version":"2013","name":"Intellectual property rights","theme":"Compliance","description":"Appropriate procedures shall be implemented to ensure compliance with legislative, regulatory and contractual requirements related to intellectual property rights and use of proprietary software products.","guidance":"The following guidelines should be considered: publishing an intellectual property rights compliance policy that defines the legal use of software and information products; acquiring software only through known and reputable sources.","control_type":["Preventive"],"related_controls":["A.18.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.18.1.3","version":"2013","name":"Protection of records","theme":"Compliance","description":"Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release, in accordance with legislative, regulatory, contractual and business requirements.","guidance":"Some records may need to be retained securely to meet statutory, regulatory and business requirements. Examples include records that may be needed to provide evidence that the organisation complies with rules for the ISMS.","control_type":["Preventive"],"related_controls":["A.18.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.18.1.4","version":"2013","name":"Privacy and protection of personally identifiable information","theme":"Compliance","description":"Privacy and protection of personally identifiable information shall be ensured as required in relevant legislation and regulations where applicable.","guidance":"A data protection and privacy policy should be developed and implemented. This policy should be communicated to all persons involved in the processing of personal information.","control_type":["Preventive"],"related_controls":["A.18.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.18.1.5","version":"2013","name":"Regulation of cryptographic controls","theme":"Compliance","description":"Cryptographic controls shall be used in compliance with all relevant agreements, legislation and regulations.","guidance":"Legal advice should be sought to ensure compliance with national laws. Before encrypted information or cryptographic controls are moved to another country or imported from another country, legal advice should be sought.","control_type":["Preventive"],"related_controls":["A.18.1.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.18.2.1","version":"2013","name":"Independent review of information security","theme":"Compliance","description":"The organization's approach to managing information security and its implementation (i.e. control objectives, controls, policies, processes and procedures for information security) shall be reviewed independently at planned intervals or when significant changes occur.","guidance":"Management should determine how independent review activities are to be carried out, by whom, and at what intervals. These activities may include internal audit or a review by a designated independent review body.","control_type":["Detective"],"related_controls":["A.18.2.2","A.18.2.3"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.18.2.2","version":"2013","name":"Compliance with security policies and standards","theme":"Compliance","description":"Managers shall regularly review the compliance of information processing and procedures within their area of responsibility with the appropriate security policies, standards and any other security requirements.","guidance":"If any non-compliance is found as a result of the review, managers should document violations and their causes, evaluate the need for actions to ensure that non-compliance does not recur, determine and implement appropriate corrective actions, and review the corrective actions taken.","control_type":["Detective"],"related_controls":["A.18.2.1"],"new_in_2022":False,"iso_clause_refs":[]},
  {"control_id":"A.18.2.3","version":"2013","name":"Technical compliance review","theme":"Compliance","description":"Information systems shall be regularly reviewed for compliance with the organization's information security policies and standards.","guidance":"Technical compliance reviews should preferably be supported by automated tools which generate technical reports for subsequent interpretation by a technical specialist. Alternatively, manual interpretation by an experienced system engineer should be carried out.","control_type":["Detective"],"related_controls":["A.18.2.1"],"new_in_2022":False,"iso_clause_refs":[]},
]

with open(os.path.join(OUT, "controls-2013.json"), "w") as f:
    json.dump(CONTROLS_2013, f, indent=2)

print(f"controls-2013.json: {len(CONTROLS_2013)} controls")
themes_2013 = {}
for c in CONTROLS_2013:
    themes_2013[c["theme"]] = themes_2013.get(c["theme"], 0) + 1
for t, n in sorted(themes_2013.items()):
    print(f"  {t}: {n}")


# ─── Version Mapping ──────────────────────────────────────────────────────────
# Maps ISO 27001:2013 controls to 2022 equivalents
VERSION_MAPPING = [
  # Direct mappings (same concept, renumbered)
  {"v2013_id":"A.5.1.1","v2022_id":"5.1","mapping_type":"direct","change_summary":"Policy for information security — renamed and scope slightly expanded","migration_notes":"The 2022 version combines A.5.1.1 and A.5.1.2 into a single control (5.1)."},
  {"v2013_id":"A.5.1.2","v2022_id":"5.1","mapping_type":"merged","change_summary":"Review of policies merged into 5.1 in 2022","migration_notes":"Review requirements are now embedded within control 5.1 rather than a separate control."},
  {"v2013_id":"A.6.1.1","v2022_id":"5.2","mapping_type":"direct","change_summary":"Roles and responsibilities — moved from A.6 to A.5 (Organizational theme)","migration_notes":"No substantive change. The control has been relocated to the Organizational theme."},
  {"v2013_id":"A.6.1.2","v2022_id":"5.3","mapping_type":"direct","change_summary":"Segregation of duties — moved from A.6 to A.5","migration_notes":"No substantive change."},
  {"v2013_id":"A.6.1.3","v2022_id":"5.5","mapping_type":"direct","change_summary":"Contact with authorities","migration_notes":"No substantive change. Renumbered only."},
  {"v2013_id":"A.6.1.4","v2022_id":"5.6","mapping_type":"direct","change_summary":"Contact with special interest groups","migration_notes":"No substantive change. Renumbered only."},
  {"v2013_id":"A.6.1.5","v2022_id":"5.8","mapping_type":"direct","change_summary":"Information security in project management","migration_notes":"No substantive change. Renumbered and moved to Organizational theme."},
  {"v2013_id":"A.6.2.1","v2022_id":"8.1","mapping_type":"merged","change_summary":"Mobile device policy merged into User endpoint devices (8.1)","migration_notes":"The 2022 control 8.1 covers all endpoint devices including mobile."},
  {"v2013_id":"A.6.2.2","v2022_id":"6.7","mapping_type":"renamed","change_summary":"Teleworking renamed to Remote working","migration_notes":"Scope slightly broadened to address all remote working scenarios."},
  {"v2013_id":"A.7.1.1","v2022_id":"6.1","mapping_type":"direct","change_summary":"Screening","migration_notes":"No substantive change. Renumbered from A.7 to A.6 (People theme)."},
  {"v2013_id":"A.7.1.2","v2022_id":"6.2","mapping_type":"direct","change_summary":"Terms and conditions of employment","migration_notes":"No substantive change. Renumbered only."},
  {"v2013_id":"A.7.2.1","v2022_id":"5.4","mapping_type":"direct","change_summary":"Management responsibilities moved to Organizational theme","migration_notes":"Renumbered from A.7 to A.5. Now named 'Management responsibilities'."},
  {"v2013_id":"A.7.2.2","v2022_id":"6.3","mapping_type":"direct","change_summary":"Awareness, education and training","migration_notes":"No substantive change. Renumbered only."},
  {"v2013_id":"A.7.2.3","v2022_id":"6.4","mapping_type":"direct","change_summary":"Disciplinary process","migration_notes":"No substantive change. Renumbered only."},
  {"v2013_id":"A.7.3.1","v2022_id":"6.5","mapping_type":"direct","change_summary":"Responsibilities after termination or change","migration_notes":"No substantive change. Renumbered only."},
  {"v2013_id":"A.8.1.1","v2022_id":"5.9","mapping_type":"merged","change_summary":"Asset inventory merged with ownership into 5.9","migration_notes":"A.8.1.1 and A.8.1.2 merged into 5.9 'Inventory of information and other associated assets'."},
  {"v2013_id":"A.8.1.2","v2022_id":"5.9","mapping_type":"merged","change_summary":"Asset ownership merged into 5.9","migration_notes":"See A.8.1.1 note."},
  {"v2013_id":"A.8.1.3","v2022_id":"5.10","mapping_type":"direct","change_summary":"Acceptable use — renumbered","migration_notes":"Renamed to 'Acceptable use of information and other associated assets'."},
  {"v2013_id":"A.8.1.4","v2022_id":"5.11","mapping_type":"direct","change_summary":"Return of assets","migration_notes":"No substantive change. Moved from Asset management to Organizational theme."},
  {"v2013_id":"A.8.2.1","v2022_id":"5.12","mapping_type":"direct","change_summary":"Classification of information","migration_notes":"No substantive change. Moved from Asset management to Organizational theme."},
  {"v2013_id":"A.8.2.2","v2022_id":"5.13","mapping_type":"direct","change_summary":"Labelling of information","migration_notes":"No substantive change."},
  {"v2013_id":"A.8.2.3","v2022_id":"5.10","mapping_type":"merged","change_summary":"Handling of assets merged into acceptable use (5.10)","migration_notes":"Asset handling requirements are now addressed within 5.10."},
  {"v2013_id":"A.8.3.1","v2022_id":"7.10","mapping_type":"merged","change_summary":"Removable media management merged into Storage media (7.10)","migration_notes":"A.8.3.1, A.8.3.2, A.8.3.3 are all addressed by 7.10 in 2022."},
  {"v2013_id":"A.8.3.2","v2022_id":"7.10","mapping_type":"merged","change_summary":"Disposal of media merged into 7.10","migration_notes":"See A.8.3.1 note."},
  {"v2013_id":"A.8.3.3","v2022_id":"7.10","mapping_type":"merged","change_summary":"Physical media transfer merged into 7.10","migration_notes":"See A.8.3.1 note."},
  {"v2013_id":"A.9.1.1","v2022_id":"5.15","mapping_type":"direct","change_summary":"Access control policy — renumbered","migration_notes":"Moved from access control domain to Organizational theme as 5.15."},
  {"v2013_id":"A.9.1.2","v2022_id":"8.20","mapping_type":"merged","change_summary":"Network access merged into Networks security (8.20)","migration_notes":"Network access requirements now addressed within broader 8.20 control."},
  {"v2013_id":"A.9.2.1","v2022_id":"5.16","mapping_type":"merged","change_summary":"User registration merged into Identity management (5.16)","migration_notes":"A.9.2.1, A.9.2.2 merged into comprehensive 5.16 Identity management."},
  {"v2013_id":"A.9.2.2","v2022_id":"5.18","mapping_type":"merged","change_summary":"User access provisioning — maps to Access rights (5.18)","migration_notes":"Access provisioning and deprovisioning covered by 5.18."},
  {"v2013_id":"A.9.2.3","v2022_id":"8.2","mapping_type":"direct","change_summary":"Privileged access rights — moved to Technological theme","migration_notes":"Renumbered to 8.2 in Technological theme."},
  {"v2013_id":"A.9.2.4","v2022_id":"5.17","mapping_type":"direct","change_summary":"Authentication information management","migration_notes":"Renamed to 'Authentication information' and moved to Organizational theme."},
  {"v2013_id":"A.9.2.5","v2022_id":"5.18","mapping_type":"merged","change_summary":"Review of access rights incorporated into 5.18","migration_notes":"Review requirements are now part of the broader 5.18 Access rights control."},
  {"v2013_id":"A.9.2.6","v2022_id":"5.18","mapping_type":"merged","change_summary":"Removal of access rights incorporated into 5.18","migration_notes":"See A.9.2.5 note."},
  {"v2013_id":"A.9.3.1","v2022_id":"5.17","mapping_type":"merged","change_summary":"Use of authentication info merged into 5.17","migration_notes":"User responsibilities for authentication information now within 5.17."},
  {"v2013_id":"A.9.4.1","v2022_id":"8.3","mapping_type":"direct","change_summary":"Information access restriction — moved to Technological theme","migration_notes":"Renumbered to 8.3 in Technological theme."},
  {"v2013_id":"A.9.4.2","v2022_id":"8.5","mapping_type":"merged","change_summary":"Secure log-on merged into Secure authentication (8.5)","migration_notes":"Log-on requirements now addressed within 8.5 Secure authentication."},
  {"v2013_id":"A.9.4.3","v2022_id":"5.17","mapping_type":"merged","change_summary":"Password management system merged into Authentication information (5.17)","migration_notes":"Password system requirements addressed within 5.17."},
  {"v2013_id":"A.9.4.4","v2022_id":"8.18","mapping_type":"direct","change_summary":"Privileged utility programs — moved to Technological theme","migration_notes":"Renumbered to 8.18 in Technological theme."},
  {"v2013_id":"A.9.4.5","v2022_id":"8.4","mapping_type":"direct","change_summary":"Access to source code — moved to Technological theme","migration_notes":"Renumbered to 8.4 in Technological theme."},
  {"v2013_id":"A.10.1.1","v2022_id":"8.24","mapping_type":"merged","change_summary":"Cryptography policy merged into Use of cryptography (8.24)","migration_notes":"A.10.1.1 and A.10.1.2 merged into single 8.24 control."},
  {"v2013_id":"A.10.1.2","v2022_id":"8.24","mapping_type":"merged","change_summary":"Key management merged into 8.24","migration_notes":"See A.10.1.1 note."},
  {"v2013_id":"A.11.1.1","v2022_id":"7.1","mapping_type":"direct","change_summary":"Physical security perimeters — renumbered","migration_notes":"No substantive change. Now in Physical theme."},
  {"v2013_id":"A.11.1.2","v2022_id":"7.2","mapping_type":"direct","change_summary":"Physical entry controls renamed to Physical entry","migration_notes":"No substantive change."},
  {"v2013_id":"A.11.1.3","v2022_id":"7.3","mapping_type":"direct","change_summary":"Securing offices, rooms and facilities","migration_notes":"No substantive change."},
  {"v2013_id":"A.11.1.4","v2022_id":"7.5","mapping_type":"direct","change_summary":"Protection from environmental threats","migration_notes":"Renamed to 'Protecting against physical and environmental threats'."},
  {"v2013_id":"A.11.1.5","v2022_id":"7.6","mapping_type":"direct","change_summary":"Working in secure areas","migration_notes":"No substantive change."},
  {"v2013_id":"A.11.1.6","v2022_id":"7.2","mapping_type":"merged","change_summary":"Delivery areas merged into Physical entry (7.2)","migration_notes":"Delivery and loading area controls now addressed within 7.2."},
  {"v2013_id":"A.11.2.1","v2022_id":"7.8","mapping_type":"direct","change_summary":"Equipment siting and protection","migration_notes":"No substantive change."},
  {"v2013_id":"A.11.2.2","v2022_id":"7.11","mapping_type":"direct","change_summary":"Supporting utilities","migration_notes":"No substantive change."},
  {"v2013_id":"A.11.2.3","v2022_id":"7.12","mapping_type":"direct","change_summary":"Cabling security","migration_notes":"No substantive change."},
  {"v2013_id":"A.11.2.4","v2022_id":"7.13","mapping_type":"direct","change_summary":"Equipment maintenance","migration_notes":"No substantive change."},
  {"v2013_id":"A.11.2.5","v2022_id":"5.11","mapping_type":"merged","change_summary":"Removal of assets merged into Return of assets (5.11)","migration_notes":"Asset removal now covered by 5.11 Return of assets."},
  {"v2013_id":"A.11.2.6","v2022_id":"7.9","mapping_type":"direct","change_summary":"Off-premises assets — renumbered","migration_notes":"No substantive change."},
  {"v2013_id":"A.11.2.7","v2022_id":"7.14","mapping_type":"direct","change_summary":"Secure disposal or reuse of equipment","migration_notes":"No substantive change."},
  {"v2013_id":"A.11.2.8","v2022_id":"7.7","mapping_type":"merged","change_summary":"Unattended equipment merged into Clear desk and screen (7.7)","migration_notes":"Unattended equipment requirements now within 7.7."},
  {"v2013_id":"A.11.2.9","v2022_id":"7.7","mapping_type":"direct","change_summary":"Clear desk and screen policy — renumbered","migration_notes":"No substantive change."},
  {"v2013_id":"A.12.1.1","v2022_id":"5.37","mapping_type":"direct","change_summary":"Documented operating procedures — moved to Organizational theme","migration_notes":"No substantive change. Renumbered to 5.37."},
  {"v2013_id":"A.12.1.2","v2022_id":"8.32","mapping_type":"direct","change_summary":"Change management — moved to Technological theme","migration_notes":"No substantive change. Renumbered to 8.32."},
  {"v2013_id":"A.12.1.3","v2022_id":"8.6","mapping_type":"direct","change_summary":"Capacity management — moved to Technological theme","migration_notes":"No substantive change."},
  {"v2013_id":"A.12.1.4","v2022_id":"8.31","mapping_type":"direct","change_summary":"Separation of development, test and production environments","migration_notes":"No substantive change."},
  {"v2013_id":"A.12.2.1","v2022_id":"8.7","mapping_type":"direct","change_summary":"Protection against malware — renumbered","migration_notes":"No substantive change."},
  {"v2013_id":"A.12.3.1","v2022_id":"8.13","mapping_type":"direct","change_summary":"Information backup","migration_notes":"No substantive change."},
  {"v2013_id":"A.12.4.1","v2022_id":"8.15","mapping_type":"merged","change_summary":"Event logging merged into Logging (8.15)","migration_notes":"A.12.4.1, A.12.4.2, A.12.4.3 merged into comprehensive 8.15 Logging control."},
  {"v2013_id":"A.12.4.2","v2022_id":"8.15","mapping_type":"merged","change_summary":"Protection of log information merged into 8.15","migration_notes":"See A.12.4.1 note."},
  {"v2013_id":"A.12.4.3","v2022_id":"8.15","mapping_type":"merged","change_summary":"Administrator logs merged into 8.15","migration_notes":"See A.12.4.1 note."},
  {"v2013_id":"A.12.4.4","v2022_id":"8.17","mapping_type":"direct","change_summary":"Clock synchronisation — moved to Technological theme","migration_notes":"No substantive change."},
  {"v2013_id":"A.12.5.1","v2022_id":"8.19","mapping_type":"direct","change_summary":"Installation of software on operational systems","migration_notes":"No substantive change."},
  {"v2013_id":"A.12.6.1","v2022_id":"8.8","mapping_type":"direct","change_summary":"Management of technical vulnerabilities","migration_notes":"No substantive change."},
  {"v2013_id":"A.12.6.2","v2022_id":"8.19","mapping_type":"merged","change_summary":"Restrictions on software installation merged into 8.19","migration_notes":"Software installation restriction requirements now within 8.19."},
  {"v2013_id":"A.12.7.1","v2022_id":"8.34","mapping_type":"direct","change_summary":"Audit controls for information systems — renumbered","migration_notes":"Renamed to 'Protection of information systems during audit testing'."},
  {"v2013_id":"A.13.1.1","v2022_id":"8.20","mapping_type":"direct","change_summary":"Network controls renamed to Networks security","migration_notes":"No substantive change."},
  {"v2013_id":"A.13.1.2","v2022_id":"8.21","mapping_type":"direct","change_summary":"Security of network services","migration_notes":"No substantive change."},
  {"v2013_id":"A.13.1.3","v2022_id":"8.22","mapping_type":"direct","change_summary":"Segregation of networks","migration_notes":"No substantive change."},
  {"v2013_id":"A.13.2.1","v2022_id":"5.14","mapping_type":"direct","change_summary":"Information transfer policies — moved to Organizational theme","migration_notes":"Renamed to 'Information transfer'."},
  {"v2013_id":"A.13.2.2","v2022_id":"5.14","mapping_type":"merged","change_summary":"Agreements on information transfer merged into 5.14","migration_notes":"Transfer agreement requirements now within 5.14."},
  {"v2013_id":"A.13.2.3","v2022_id":"5.14","mapping_type":"merged","change_summary":"Electronic messaging merged into 5.14","migration_notes":"Electronic messaging requirements now within 5.14."},
  {"v2013_id":"A.13.2.4","v2022_id":"6.6","mapping_type":"direct","change_summary":"Confidentiality/NDA agreements — moved to People theme","migration_notes":"Renamed to 'Confidentiality or non-disclosure agreements'."},
  {"v2013_id":"A.14.1.1","v2022_id":"8.26","mapping_type":"direct","change_summary":"Security requirements analysis — moved to Technological theme","migration_notes":"Renamed to 'Application security requirements'."},
  {"v2013_id":"A.14.1.2","v2022_id":"8.26","mapping_type":"merged","change_summary":"Application services on public networks merged into 8.26","migration_notes":"Public-facing application requirements now within 8.26."},
  {"v2013_id":"A.14.1.3","v2022_id":"8.26","mapping_type":"merged","change_summary":"Application service transactions merged into 8.26","migration_notes":"Transaction security requirements now within 8.26."},
  {"v2013_id":"A.14.2.1","v2022_id":"8.25","mapping_type":"direct","change_summary":"Secure development policy renamed to Secure development life cycle","migration_notes":"Renamed to 8.25."},
  {"v2013_id":"A.14.2.2","v2022_id":"8.32","mapping_type":"merged","change_summary":"System change control merged into Change management (8.32)","migration_notes":"Development change control now within broader 8.32."},
  {"v2013_id":"A.14.2.3","v2022_id":"8.32","mapping_type":"merged","change_summary":"Technical review after platform changes merged into 8.32","migration_notes":"Platform change review requirements within 8.32."},
  {"v2013_id":"A.14.2.4","v2022_id":"8.19","mapping_type":"merged","change_summary":"Restrictions on software packages merged into 8.19","migration_notes":"Software change restrictions now within 8.19."},
  {"v2013_id":"A.14.2.5","v2022_id":"8.27","mapping_type":"direct","change_summary":"Secure system engineering principles","migration_notes":"Renamed to 'Secure system architecture and engineering principles'."},
  {"v2013_id":"A.14.2.6","v2022_id":"8.31","mapping_type":"merged","change_summary":"Secure development environment merged into 8.31","migration_notes":"Development environment requirements now within 8.31."},
  {"v2013_id":"A.14.2.7","v2022_id":"8.30","mapping_type":"direct","change_summary":"Outsourced development","migration_notes":"No substantive change."},
  {"v2013_id":"A.14.2.8","v2022_id":"8.29","mapping_type":"merged","change_summary":"System security testing merged into Security testing (8.29)","migration_notes":"A.14.2.8 and A.14.2.9 merged into 8.29."},
  {"v2013_id":"A.14.2.9","v2022_id":"8.29","mapping_type":"merged","change_summary":"Acceptance testing merged into 8.29","migration_notes":"See A.14.2.8 note."},
  {"v2013_id":"A.14.3.1","v2022_id":"8.33","mapping_type":"direct","change_summary":"Protection of test data renamed to Test information","migration_notes":"No substantive change."},
  {"v2013_id":"A.15.1.1","v2022_id":"5.19","mapping_type":"direct","change_summary":"Supplier security policy — moved to Organizational theme","migration_notes":"Renamed to 'Information security in supplier relationships'."},
  {"v2013_id":"A.15.1.2","v2022_id":"5.20","mapping_type":"direct","change_summary":"Addressing security in supplier agreements","migration_notes":"No substantive change."},
  {"v2013_id":"A.15.1.3","v2022_id":"5.21","mapping_type":"direct","change_summary":"ICT supply chain","migration_notes":"Renamed to 'Managing information security in the ICT supply chain'."},
  {"v2013_id":"A.15.2.1","v2022_id":"5.22","mapping_type":"direct","change_summary":"Monitoring and review of supplier services","migration_notes":"Renamed to 'Monitoring, review and change management of supplier services'."},
  {"v2013_id":"A.15.2.2","v2022_id":"5.22","mapping_type":"merged","change_summary":"Managing changes to supplier services merged into 5.22","migration_notes":"Change management requirements now within 5.22."},
  {"v2013_id":"A.16.1.1","v2022_id":"5.24","mapping_type":"direct","change_summary":"Incident management planning — moved to Organizational theme","migration_notes":"Renamed to 'Information security incident management planning and preparation'."},
  {"v2013_id":"A.16.1.2","v2022_id":"6.8","mapping_type":"direct","change_summary":"Reporting information security events — moved to People theme","migration_notes":"Renamed to 'Information security event reporting'."},
  {"v2013_id":"A.16.1.3","v2022_id":"6.8","mapping_type":"merged","change_summary":"Reporting weaknesses merged into 6.8","migration_notes":"Weakness reporting requirements now within 6.8."},
  {"v2013_id":"A.16.1.4","v2022_id":"5.25","mapping_type":"direct","change_summary":"Assessment of information security events","migration_notes":"Renamed to 'Assessment and decision on information security events'."},
  {"v2013_id":"A.16.1.5","v2022_id":"5.26","mapping_type":"direct","change_summary":"Response to incidents","migration_notes":"No substantive change."},
  {"v2013_id":"A.16.1.6","v2022_id":"5.27","mapping_type":"direct","change_summary":"Learning from incidents","migration_notes":"No substantive change."},
  {"v2013_id":"A.16.1.7","v2022_id":"5.28","mapping_type":"direct","change_summary":"Collection of evidence","migration_notes":"No substantive change."},
  {"v2013_id":"A.17.1.1","v2022_id":"5.29","mapping_type":"merged","change_summary":"Continuity planning merged into 5.29 and 5.30","migration_notes":"A.17.1.1 and A.17.1.2 merged into 5.29; ICT readiness split into new 5.30."},
  {"v2013_id":"A.17.1.2","v2022_id":"5.29","mapping_type":"merged","change_summary":"Implementing information security continuity merged into 5.29","migration_notes":"See A.17.1.1 note."},
  {"v2013_id":"A.17.1.3","v2022_id":"5.29","mapping_type":"merged","change_summary":"Verify/review continuity merged into 5.29","migration_notes":"Verification requirements within 5.29."},
  {"v2013_id":"A.17.2.1","v2022_id":"8.14","mapping_type":"direct","change_summary":"Availability/redundancy — moved to Technological theme","migration_notes":"Renamed to 'Redundancy of information processing facilities'."},
  {"v2013_id":"A.18.1.1","v2022_id":"5.31","mapping_type":"direct","change_summary":"Legal and regulatory requirements — moved to Organizational theme","migration_notes":"Renamed to 'Legal, statutory, regulatory and contractual requirements'."},
  {"v2013_id":"A.18.1.2","v2022_id":"5.32","mapping_type":"direct","change_summary":"Intellectual property rights","migration_notes":"No substantive change."},
  {"v2013_id":"A.18.1.3","v2022_id":"5.33","mapping_type":"direct","change_summary":"Protection of records","migration_notes":"No substantive change."},
  {"v2013_id":"A.18.1.4","v2022_id":"5.34","mapping_type":"direct","change_summary":"Privacy and protection of PII","migration_notes":"No substantive change."},
  {"v2013_id":"A.18.1.5","v2022_id":"8.24","mapping_type":"merged","change_summary":"Regulation of cryptographic controls merged into Use of cryptography (8.24)","migration_notes":"Compliance requirements for cryptography now within 8.24."},
  {"v2013_id":"A.18.2.1","v2022_id":"5.35","mapping_type":"direct","change_summary":"Independent review of information security","migration_notes":"No substantive change."},
  {"v2013_id":"A.18.2.2","v2022_id":"5.36","mapping_type":"direct","change_summary":"Compliance with security policies — moved to Organizational theme","migration_notes":"Renamed to 'Compliance with policies, rules and standards for information security'."},
  {"v2013_id":"A.18.2.3","v2022_id":"5.36","mapping_type":"merged","change_summary":"Technical compliance review merged into 5.36","migration_notes":"Technical compliance review now within 5.36."},
  # New 2022 controls (no 2013 equivalent)
  {"v2013_id":None,"v2022_id":"5.7","mapping_type":"new_2022","change_summary":"Threat intelligence — new control in ISO 27001:2022","migration_notes":"No direct mapping from 2013. Organisations should establish a threat intelligence capability."},
  {"v2013_id":None,"v2022_id":"5.23","mapping_type":"new_2022","change_summary":"Information security for use of cloud services — new in 2022","migration_notes":"No direct mapping from 2013. Cloud service security requirements are now explicitly addressed."},
  {"v2013_id":None,"v2022_id":"5.30","mapping_type":"new_2022","change_summary":"ICT readiness for business continuity — new in 2022","migration_notes":"Partially derived from A.17 but significantly expanded. Requires specific ICT continuity planning."},
  {"v2013_id":None,"v2022_id":"7.4","mapping_type":"new_2022","change_summary":"Physical security monitoring — new in 2022","migration_notes":"No direct mapping from 2013. Requires implementation of physical monitoring (CCTV, alarms, etc.)."},
  {"v2013_id":None,"v2022_id":"8.9","mapping_type":"new_2022","change_summary":"Configuration management — new in 2022","migration_notes":"Partially implied by A.12 but now explicit. Requires formal configuration management programme."},
  {"v2013_id":None,"v2022_id":"8.10","mapping_type":"new_2022","change_summary":"Information deletion — new in 2022","migration_notes":"No direct mapping from 2013. Requires formal procedures for secure information deletion."},
  {"v2013_id":None,"v2022_id":"8.11","mapping_type":"new_2022","change_summary":"Data masking — new in 2022","migration_notes":"No direct mapping from 2013. Requires data masking controls for sensitive data."},
  {"v2013_id":None,"v2022_id":"8.12","mapping_type":"new_2022","change_summary":"Data leakage prevention — new in 2022","migration_notes":"No direct mapping from 2013. Requires DLP controls across endpoints, network, and cloud."},
  {"v2013_id":None,"v2022_id":"8.16","mapping_type":"new_2022","change_summary":"Monitoring activities — new in 2022","migration_notes":"Partially covered by A.12.4 logging controls but significantly expanded."},
  {"v2013_id":None,"v2022_id":"8.23","mapping_type":"new_2022","change_summary":"Web filtering — new in 2022","migration_notes":"No direct mapping from 2013. Requires web filtering capability."},
  {"v2013_id":None,"v2022_id":"8.28","mapping_type":"new_2022","change_summary":"Secure coding — new in 2022","migration_notes":"Partially implied by A.14.2 but now explicit. Requires formal secure coding standards."},
]

with open(os.path.join(OUT, "version-mapping.json"), "w") as f:
    json.dump(VERSION_MAPPING, f, indent=2)

print(f"\nversion-mapping.json: {len(VERSION_MAPPING)} mappings")
types = {}
for m in VERSION_MAPPING:
    types[m["mapping_type"]] = types.get(m["mapping_type"], 0) + 1
for t, n in sorted(types.items()):
    print(f"  {t}: {n}")
