/**
 * Unit tests for src/tools/evidence-templates.ts
 *
 * Covers:
 *  - handleGenerateEvidenceDocument (template rendering, dual DB write,
 *    org-profile injection, vars merge)
 *  - handleGetEvidenceDocument (found / not-found)
 *  - handleListEvidenceDocuments (filters, pagination)
 */

import { describe, it, expect, vi, beforeEach } from "vitest";

// ── Module-level mock stubs ───────────────────────────────────

const mockStmt = {
  get:  vi.fn(),
  all:  vi.fn(() => []),
  run:  vi.fn(() => ({ changes: 1 })),
};

const mockDb = {
  prepare: vi.fn(() => mockStmt),
};

vi.mock("../../../src/db/connection.js", () => ({
  getDb: vi.fn(() => mockDb),
}));

// Template-utils mock — loadTemplate returns a minimal Mustache template
vi.mock("../../../src/tools/template-utils.js", () => ({
  loadTemplate: vi.fn((_type: string, _dir: string) =>
    `---\ntemplate_type: {{template_type}}\nclause_mappings: ["9.1"]\ncontrol_mappings: ["5.15"]\n---\n# {{title}}\n\nOrg: {{organisation_name}}\nGenerated by: {{generated_by}}\n`,
  ),
  stripFrontmatter: vi.fn((raw: string) => {
    const match = raw.match(/^---\n[\s\S]*?\n---\n([\s\S]*)$/);
    return {
      template:       match ? match[1] : raw,
      clauseMappings: ["9.1"],
      controlMappings: ["5.15"],
    };
  }),
  // loadPartials returns empty object — partials not needed in unit tests
  loadPartials: vi.fn(() => ({})),
}));

// org-profile mock — loadOrgProfileDefaults returns null by default
vi.mock("../../../src/tools/org-profile.js", () => ({
  loadOrgProfileDefaults: vi.fn(() => null),
}));

// SUT imports (after vi.mock)
import {
  handleGenerateEvidenceDocument,
  handleGetEvidenceDocument,
  handleListEvidenceDocuments,
} from "../../../src/tools/evidence-templates.js";
import { McpError } from "../../../src/types/errors.js";

// Import mocked module at top level so it can be re-configured per test
import { loadOrgProfileDefaults as mockLoadOrgProfileDefaults } from "../../../src/tools/org-profile.js";

// ── Helpers ───────────────────────────────────────────────────

function parse(r: { content: Array<{ type: string; text: string }>; isError: boolean }) {
  return JSON.parse(r.content[0].text) as Record<string, unknown>;
}

const DOC_ROW = {
  id:                "doc-1",
  template_type:     "access_review_attestation",
  title:             "Q1 2025 Access Review",
  content:           "# Q1 2025 Access Review\n\nOrg: Acme Corp\n",
  organisation_name: "Acme Corp",
  generated_by:      "alice",
  clause_mappings:   JSON.stringify(["9.1"]),
  control_mappings:  JSON.stringify(["5.15"]),
  template_vars:     JSON.stringify({ reviewer_name: "Alice" }),
  evidence_id:       "ev-1",
  created_at:        "2025-03-31T10:00:00Z",
};

// ── Tests ─────────────────────────────────────────────────────

describe("handleGenerateEvidenceDocument", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    // Mock the org profile RACI query (returns undefined = no profile)
    mockStmt.get.mockReturnValue(undefined);
  });

  it("renders template, writes evidence row, writes generated_evidence row, returns content", () => {
    const result = handleGenerateEvidenceDocument({
      template_type:     "access_review_attestation",
      title:             "Q1 2025 Access Review",
      generated_by:      "alice",
      organisation_name: "Acme Corp",
      vars:              { reviewer_name: "Alice Smith" },
    });

    expect(result.isError).toBe(false);
    const data = parse(result);

    expect(data.template_type).toBe("access_review_attestation");
    expect(data.title).toBe("Q1 2025 Access Review");
    expect(typeof data.document_id).toBe("string");
    expect(typeof data.evidence_id).toBe("string");
    expect(typeof data.content).toBe("string");
    expect((data.content as string).length).toBeGreaterThan(0);

    // Two INSERT calls: evidence + generated_evidence
    expect(mockStmt.run).toHaveBeenCalledTimes(2);
  });

  it("uses caller-supplied organisation_name in preference to org profile", () => {
    vi.mocked(mockLoadOrgProfileDefaults).mockReturnValue({
      organisation_name: "Profile Corp",
      scope:             "All systems",
    });

    const result = handleGenerateEvidenceDocument({
      template_type:     "training_acknowledgement",
      title:             "Awareness Training Record",
      generated_by:      "hr",
      organisation_name: "Caller Corp",   // should win
      vars:              {},
    });

    const data = parse(result);
    expect(data.organisation_name).toBe("Caller Corp");
  });

  it("falls back to org profile organisation_name when caller omits it", () => {
    vi.mocked(mockLoadOrgProfileDefaults).mockReturnValue({
      organisation_name: "Profile Corp",
      scope:             "All systems",
    });

    const result = handleGenerateEvidenceDocument({
      template_type: "bcp_test_report",
      title:         "BCP Tabletop 2025",
      generated_by:  "bcm-lead",
      vars:          {},
    });

    const data = parse(result);
    expect(data.organisation_name).toBe("Profile Corp");
  });

  it("returns clause_mappings and control_mappings from template frontmatter", () => {
    const result = handleGenerateEvidenceDocument({
      template_type: "risk_treatment_sign_off",
      title:         "Risk Sign-Off — R001",
      generated_by:  "ciso",
      vars:          {},
    });

    const data = parse(result);
    expect(Array.isArray(data.clause_mappings)).toBe(true);
    expect(Array.isArray(data.control_mappings)).toBe(true);
  });

  it("uses 'general' as control_id when none supplied", () => {
    handleGenerateEvidenceDocument({
      template_type: "incident_post_mortem",
      title:         "Post-Mortem: DB Outage",
      generated_by:  "sre",
      vars:          {},
    });

    // First run() call is the evidence INSERT
    const firstRunArgs = mockStmt.run.mock.calls[0] as unknown[];
    // control_id is the 2nd positional arg (after id)
    expect(firstRunArgs[1]).toBe("general");
  });

  it("uses caller-supplied control_id when provided", () => {
    handleGenerateEvidenceDocument({
      template_type: "supplier_security_questionnaire",
      title:         "Vendor Assessment — Acme Cloud",
      generated_by:  "procurement",
      control_id:    "5.19",
      vars:          {},
    });

    const firstRunArgs = mockStmt.run.mock.calls[0] as unknown[];
    expect(firstRunArgs[1]).toBe("5.19");
  });
});

describe("handleGetEvidenceDocument", () => {
  beforeEach(() => vi.clearAllMocks());

  it("returns document with parsed arrays and template_vars", () => {
    mockStmt.get.mockReturnValueOnce(DOC_ROW);

    const result = handleGetEvidenceDocument({ document_id: "doc-1" });

    expect(result.isError).toBe(false);
    const data = parse(result);
    expect(data.id).toBe("doc-1");
    expect(data.template_type).toBe("access_review_attestation");
    expect(Array.isArray(data.clause_mappings)).toBe(true);
    expect(typeof data.template_vars).toBe("object");
    const tv = data.template_vars as Record<string, string>;
    expect(tv.reviewer_name).toBe("Alice");
  });

  it("throws NOT_FOUND for unknown document_id", () => {
    mockStmt.get.mockReturnValue(undefined);

    expect(() => handleGetEvidenceDocument({ document_id: "ghost" })).toThrow(McpError);
  });
});

describe("handleListEvidenceDocuments", () => {
  beforeEach(() => vi.clearAllMocks());

  it("returns paginated list with no filter", () => {
    mockStmt.all.mockReturnValue([DOC_ROW]);

    const result = handleListEvidenceDocuments({ limit: 10, offset: 0 });

    expect(result.isError).toBe(false);
    const data = parse(result);
    expect(Array.isArray(data.documents)).toBe(true);
    const docs = data.documents as Array<Record<string, unknown>>;
    expect(docs[0]?.id).toBe("doc-1");
    expect(Array.isArray(docs[0]?.clause_mappings)).toBe(true);
  });

  it("applies template_type filter", () => {
    mockStmt.all.mockReturnValue([]);

    handleListEvidenceDocuments({ template_type: "bcp_test_report" });

    const sql = mockDb.prepare.mock.calls[0]?.[0] as string;
    expect(sql).toContain("template_type = ?");
  });

  it("applies generated_by filter", () => {
    mockStmt.all.mockReturnValue([]);

    handleListEvidenceDocuments({ generated_by: "alice" });

    const sql = mockDb.prepare.mock.calls[0]?.[0] as string;
    expect(sql).toContain("generated_by = ?");
  });

  it("applies control_id filter with LEFT JOIN", () => {
    mockStmt.all.mockReturnValue([]);

    handleListEvidenceDocuments({ control_id: "5.15" });

    const sql = mockDb.prepare.mock.calls[0]?.[0] as string;
    expect(sql).toContain("LEFT JOIN evidence");
    expect(sql).toContain("control_id = ?");
  });

  it("returns empty documents array when no records exist", () => {
    mockStmt.all.mockReturnValue([]);

    const result = handleListEvidenceDocuments({});
    const data   = parse(result);
    expect(data.total).toBe(0);
    expect(data.documents).toEqual([]);
  });
});
