/**
 * ARD publishing artefact validation.
 *
 * Validates docs/ard.json against the vendored authoritative ARD entry schema
 * (ards-project/ard-spec, ARD v0.91) and locks in drift guards between the
 * generated artefacts and their sources of truth (package.json version,
 * tool registry, ARD discovery constraints §D.2).
 *
 * The artefacts are regenerated by scripts/generate-ard.ts (wired into
 * `npm run postbuild`) — if these tests fail after a registry or version
 * change, run: npx tsx scripts/generate-ard.ts
 */

import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import { TOOLS } from "../../src/tools/registry.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

interface ArdEntry {
  "@context"?: string;
  identifier: string;
  displayName: string;
  type: string;
  url?: string;
  data?: object;
  representativeQueries?: string[];
  capabilities?: string[];
  version?: string;
  updatedAt?: string;
}
interface ArdManifest { entries: ArdEntry[] }
interface ServerCard { version: string; toolCount: number; tools: { name: string }[] }

const schema   = JSON.parse(readFileSync(join(root, "tests", "fixtures", "ard-entry.schema.json"), "utf8")) as Record<string, unknown>;
const manifest = JSON.parse(readFileSync(join(root, "docs", "ard.json"), "utf8")) as ArdManifest;
const card     = JSON.parse(readFileSync(join(root, "docs", "server-card.json"), "utf8")) as ServerCard;
const pkg      = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as { version: string };

const ajv = new Ajv2020({ strict: false });
addFormats(ajv);
ajv.addSchema(schema);

describe("ARD manifest — schema validity (authoritative ard-entry.schema.json)", () => {
  it("docs/ard.json validates as an ArdManifest", () => {
    const validate = ajv.getSchema(`${schema["$id"] as string}#/$defs/ArdManifest`);
    expect(validate).toBeDefined();
    const valid = validate!(manifest);
    expect(validate!.errors ?? []).toEqual([]);
    expect(valid).toBe(true);
  });

  it("every entry validates as an ArdEntry", () => {
    const validate = ajv.getSchema(`${schema["$id"] as string}#/$defs/ArdEntry`);
    expect(validate).toBeDefined();
    for (const entry of manifest.entries) {
      const valid = validate!(entry);
      expect(validate!.errors ?? []).toEqual([]);
      expect(valid).toBe(true);
    }
  });
});

describe("ARD manifest — discovery constraints (spec §D.2, §4.2)", () => {
  const entry = manifest.entries[0]!;

  it("has exactly one entry for this server", () => {
    expect(manifest.entries).toHaveLength(1);
  });

  it("identifier uses the domain-anchored URN with our publisher domain", () => {
    expect(entry.identifier).toBe("urn:air:sushegaad.github.io:server:iso27001-mcp");
    expect(entry.identifier).toMatch(/^urn:air:[a-zA-Z0-9.-]+(:[a-zA-Z0-9._-]+)+$/);
  });

  it("carries exactly one of url/data (value-or-reference rule)", () => {
    expect(entry.url).toBeDefined();
    expect(entry.data).toBeUndefined();
  });

  it("representativeQueries has 2-5 examples (semantic index signal)", () => {
    expect(entry.representativeQueries).toBeDefined();
    expect(entry.representativeQueries!.length).toBeGreaterThanOrEqual(2);
    expect(entry.representativeQueries!.length).toBeLessThanOrEqual(5);
    for (const q of entry.representativeQueries!) {
      expect(q.length).toBeGreaterThan(10);
    }
  });

  it("declares the ARD base context (required for in-page JSON-LD embedding)", () => {
    expect(entry["@context"]).toBe("https://agenticresourcediscovery.org/context/v1");
  });

  it("type is the MCP server card media type", () => {
    expect(entry.type).toBe("application/mcp-server-card+json");
  });

  it("url points at the hosted server card on the publisher domain", () => {
    expect(entry.url).toBe("https://sushegaad.github.io/MCP-Server-for-ISO27001/server-card.json");
    // The URL's host must match the URN publisher segment
    const publisher = entry.identifier.split(":")[2]!;
    expect(new URL(entry.url!).host).toBe(publisher);
  });
});

describe("ARD artefacts — drift guards against sources of truth", () => {
  const entry = manifest.entries[0]!;

  it("entry version matches package.json", () => {
    expect(entry.version).toBe(pkg.version);
  });

  it("server card version matches package.json", () => {
    expect(card.version).toBe(pkg.version);
  });

  it("server card tool count equals the registry TOOLS length", () => {
    expect(card.toolCount).toBe(TOOLS.length);
    expect(card.tools).toHaveLength(TOOLS.length);
  });

  it("server card tool names exactly match the registry", () => {
    const cardNames = card.tools.map((t) => t.name).sort();
    const regNames  = TOOLS.map((t) => t.name).sort();
    expect(cardNames).toEqual(regNames);
  });

  it("updatedAt is a valid ISO 8601 date-time", () => {
    expect(entry.updatedAt).toBeDefined();
    expect(Number.isNaN(Date.parse(entry.updatedAt!))).toBe(false);
    expect(entry.updatedAt).toMatch(/^\d{4}-\d{2}-\d{2}T/);
  });

  it("well-known copy is byte-identical to docs/ard.json", () => {
    const wkPath = join(root, "wellknown-site", ".well-known", "ard.json");
    expect(existsSync(wkPath)).toBe(true);
    expect(readFileSync(wkPath, "utf8")).toBe(readFileSync(join(root, "docs", "ard.json"), "utf8"));
  });

  it("docs/index.html carries the rel=ard link and the in-page JSON-LD entry", () => {
    const html = readFileSync(join(root, "docs", "index.html"), "utf8");
    expect(html).toContain('rel="ard"');
    expect(html).toContain("https://sushegaad.github.io/MCP-Server-for-ISO27001/ard.json");
    expect(html).toContain('type="application/ld+json"');
    expect(html).toContain(entry.identifier);
  });
});
